export const countryCodes = [
  // 🇺🇸 North America
  { code: "+1", country: "United States / Canada" },
  { code: "+1-242", country: "Bahamas" },
  { code: "+1-246", country: "Barbados" },
  { code: "+1-268", country: "Antigua and Barbuda" },
  { code: "+1-284", country: "British Virgin Islands" },
  { code: "+1-441", country: "Bermuda" },
  { code: "+1-473", country: "Grenada" },
  { code: "+1-664", country: "Montserrat" },
  { code: "+1-721", country: "Sint Maarten" },
  { code: "+1-758", country: "Saint Lucia" },
  { code: "+1-767", country: "Dominica" },
  { code: "+1-784", country: "Saint Vincent and the Grenadines" },
  { code: "+1-809", country: "Dominican Republic" },
  { code: "+1-868", country: "Trinidad and Tobago" },
  { code: "+1-876", country: "Jamaica" },
  { code: "+52", country: "Mexico" }

  // 🇪🇺 Europe
  ,{ code: "+44", country: "United Kingdom" },
  { code: "+33", country: "France" },
  { code: "+49", country: "Germany" },
  { code: "+39", country: "Italy" },
  { code: "+34", country: "Spain" },
  { code: "+31", country: "Netherlands" },
  { code: "+41", country: "Switzerland" },
  { code: "+46", country: "Sweden" },
  { code: "+45", country: "Denmark" },
  { code: "+47", country: "Norway" },
  { code: "+358", country: "Finland" },
  { code: "+43", country: "Austria" },
  { code: "+353", country: "Ireland" },
  { code: "+48", country: "Poland" },
  { code: "+420", country: "Czech Republic" },
  { code: "+421", country: "Slovakia" },
  { code: "+36", country: "Hungary" },
  { code: "+40", country: "Romania" },
  { code: "+351", country: "Portugal" },
  { code: "+30", country: "Greece" },
  { code: "+386", country: "Slovenia" },
  { code: "+385", country: "Croatia" },
  { code: "+389", country: "North Macedonia" },
  { code: "+380", country: "Ukraine" },
  { code: "+7", country: "Russia" },
  { code: "+372", country: "Estonia" },
  { code: "+371", country: "Latvia" },
  { code: "+370", country: "Lithuania" },
  { code: "+357", country: "Cyprus" },
  { code: "+356", country: "Malta" }
  
  // 🌍 Middle East
  ,{ code: "+971", country: "United Arab Emirates" },
  { code: "+966", country: "Saudi Arabia" },
  { code: "+974", country: "Qatar" },
  { code: "+973", country: "Bahrain" },
  { code: "+968", country: "Oman" },
  { code: "+965", country: "Kuwait" },
  { code: "+964", country: "Iraq" },
  { code: "+962", country: "Jordan" },
  { code: "+963", country: "Syria" },
  { code: "+972", country: "Israel" },
  { code: "+98", country: "Iran" },
  { code: "+90", country: "Turkey" }

  // 🇦🇸 Asia Pacific
  ,{ code: "+91", country: "India" },
  { code: "+92", country: "Pakistan" },
  { code: "+880", country: "Bangladesh" },
  { code: "+94", country: "Sri Lanka" },
  { code: "+975", country: "Bhutan" },
  { code: "+977", country: "Nepal" },
  { code: "+86", country: "China" },
  { code: "+81", country: "Japan" },
  { code: "+82", country: "South Korea" },
  { code: "+65", country: "Singapore" },
  { code: "+60", country: "Malaysia" },
  { code: "+62", country: "Indonesia" },
  { code: "+63", country: "Philippines" },
  { code: "+66", country: "Thailand" },
  { code: "+84", country: "Vietnam" },
  { code: "+95", country: "Myanmar" },
  { code: "+855", country: "Cambodia" },
  { code: "+856", country: "Laos" },
  { code: "+853", country: "Macau" },
  { code: "+886", country: "Taiwan" },
  { code: "+852", country: "Hong Kong" },
  { code: "+64", country: "New Zealand" },
  { code: "+61", country: "Australia" }

  // 🌍 Africa
  ,{ code: "+27", country: "South Africa" },
  { code: "+234", country: "Nigeria" },
  { code: "+20", country: "Egypt" },
  { code: "+256", country: "Uganda" },
  { code: "+254", country: "Kenya" },
  { code: "+251", country: "Ethiopia" },
  { code: "+233", country: "Ghana" },
  { code: "+212", country: "Morocco" },
  { code: "+213", country: "Algeria" },
  { code: "+216", country: "Tunisia" },
  { code: "+218", country: "Libya" },
  { code: "+221", country: "Senegal" },
  { code: "+225", country: "Ivory Coast" },
  { code: "+255", country: "Tanzania" },
  { code: "+260", country: "Zambia" },
  { code: "+263", country: "Zimbabwe" },
  { code: "+248", country: "Seychelles" }

  // 🌎 South America
  ,{ code: "+55", country: "Brazil" },
  { code: "+54", country: "Argentina" },
  { code: "+56", country: "Chile" },
  { code: "+57", country: "Colombia" },
  { code: "+58", country: "Venezuela" },
  { code: "+51", country: "Peru" },
  { code: "+595", country: "Paraguay" },
  { code: "+598", country: "Uruguay" },
  { code: "+591", country: "Bolivia" },
  { code: "+593", country: "Ecuador" }
];
