// export const heroStats = [
//   ["7", "frontier AI labs served"],
//   ["30+", "startups served"],
//   ["20B+", "tokens"],
//   ["57+", "languages"],
// ];

export const heroContent = {
  eyebrow: "Training Intelligence Infrastructure",
 
  headline: [
    "Enterprise AI is only as trustworthy as",
    "what it learned.",        
  ],
 
  subtext:
    "InfoBay engineers the expert-verified training data, annotation infrastructure, and evaluation systems that make AI accurate, factual, and production-ready — grounded in 1.91M+ hours of multilingual audio across 40+ languages, 1.6M+ patient medical records, academic textbooks in 15 languages, and 64K+ coding problems.",
 
  ctas: [
    { label: "Request a Model Quality Audit", href: "#contact",    variant: "primary" },
    { label: "Explore the Corpus →",          href: "#corpus", variant: "ghost"   },
  ],
 
  scripts: "Arabic · Bahasa · Swahili · French · Nepali · Urdu · Bengali · Portuguese · Bahasa · Java · Python · C++",
};

export const heroStats = [
  {
    value: "1.96M+",
    label: "Call Center Audio Hours",
    note:  "English · Arabic · French · Swahili · Portuguese · Nepali · 35+ languages",
    wide:  false,
  },
  {
    value: "57K+",
    label: "Podcast Hours",
    note:  "12 languages · natural long-form speech",
    wide:  false,
  },
  {
    value: "15",
    label: "Textbook Languages",
    note:  "ISBN-attributed · STEM + Non-STEM · 5,000+ subjects",
    wide:  false,
  },
  {
    value: "2B+",
    label: "Total Data Samples",
    note:  "53M+ medical Images & Files · MRI · CT · X-ray",
    wide:  false,
  },
  {
    value: "25M+",
    label: "Coding Tokens — 9 languages · 64K+ DSA problems · Java · Python · C++ · JavaScript · C# · PHP",
    note:  null,
    wide:  true,
  },
];

// export const corpusTabs = [
//   {
//     id: "audio",
//     label: "Audio",
//     title: "1.96M+ hours of multilingual audio",
//     summary:
//       "Call center, podcast, and speech intelligence datasets with premium metadata for gender, age, industry, channel, dialect, and language.",
//     accent: "from-cyan-300/30 to-blue-400/10",
//     metrics: [
//       ["1,912,393", "call center hours"],
//       ["57,568", "podcast hours"],
//       ["57+", "languages"],
//       ["35+", "additional language families"],
//       ["4", "audio refining steps"],
//       ["Dual", "channel support"],
//     ],
//     tableTitle: "High-volume coverage",
//     table: [
//       ["Hindi", "582,745 hrs"],
//       ["Bengali", "377,048 hrs"],
//       ["Nepali", "235,410 hrs"],
//       ["English India", "170,166 hrs"],
//       ["English US", "127,536 hrs"],
//       ["English UK", "90,334 hrs"],
//       ["Assamese", "58,478 hrs"],
//       ["Arabic", "24,739 hrs"],
//     ],
//     notes: [
//       "Duplicate asset elimination for uniqueness and consistency.",
//       "Low-activity voice removal, PII detection and muting, and background noise cleanup.",
//       "Podcast coverage includes Arabic, Bengali, Hindi, Tamil, Telugu, Urdu, Marathi, Gujarati, Kannada, Malayalam, Punjabi, and English.",
//     ],
//   },
//   {
//     id: "video",
//     label: "Video",
//     title: "130K+ hours of structured and UGC video",
//     summary:
//       "STEM classroom and vertical UGC video designed for multimodal grounding, visual reasoning, and cross-modal alignment.",
//     accent: "from-emerald-300/25 to-cyan-400/10",
//     metrics: [
//       ["100K+", "STEM classroom hours"],
//       ["30K+", "UGC hours"],
//       ["4.5M", "UGC videos"],
//       ["8", "video refining steps"],
//       ["AV1", "codec audit"],
//       ["OCR", "text recognition"],
//     ],
//     tableTitle: "Refining process",
//     table: [
//       ["01", "Duplicate asset elimination"],
//       ["02", "Vertical format validation"],
//       ["03", "AV1 codec audit"],
//       ["04", "Intelligent text recognition"],
//       ["05", "Animated content classification"],
//       ["06", "AI synthetic media detection"],
//       ["07", "Brand logo intelligence"],
//       ["08", "Watermark integrity analysis"],
//     ],
//     notes: [
//       "Classroom content is suitable for STEM reasoning and lecture understanding.",
//       "Vertical UGC supports short-form visual grounding and noisy real-world formats.",
//     ],
//   },
//   {
//     id: "healthcare",
//     label: "Healthcare",
//     title: "53M+ healthcare files from verified providers",
//     summary:
//       "De-identified diagnostic imaging, clinical records, findings, prescriptions, pathology, and longitudinal care datasets.",
//     accent: "from-rose-300/25 to-cyan-400/10",
//     metrics: [
//       ["1.6M+", "patients"],
//       ["53M+", "files and images"],
//       ["26.8M", "CT images"],
//       ["24.8M", "MRI images"],
//       ["626K", "X-Ray images"],
//       ["376K", "HIV ART records"],
//     ],
//     tableTitle: "Dataset breakdown",
//     table: [
//       ["MRI", "77,937 patients + 24,882,631 images"],
//       ["CT Scan", "144,847 patients + 26,851,494 images"],
//       ["IPD and IVF discharge", "436,801 files"],
//       ["Dermatology and OPD", "315,411 images"],
//       ["X-Ray", "250,424 patients + 626,954 images"],
//       ["USG", "2,974 patients + 9,039 images"],
//       ["Pathology", "35,894 files"],
//       ["Longitudinal HIV ART", "376,236 files"],
//     ],
//     notes: [
//       "Provider-sourced medical samples are de-identified for privacy.",
//       "Clinical validation and standardization support AI readiness.",
//     ],
//   },
//   {
//     id: "textbook",
//     label: "Textbook",
//     title: "2.4B+ words from 35,000+ textbooks",
//     summary:
//       "Licensed textbook corpus spanning 15 languages, 5,000+ subjects, and interwoven visuals for contextual model learning.",
//     accent: "from-amber-300/25 to-cyan-400/10",
//     metrics: [
//       ["35K+", "books"],
//       ["2.4B+", "words"],
//       ["15", "languages"],
//       ["5,000+", "subjects"],
//       ["12,125", "English books"],
//       ["6,307", "Bahasa books"],
//     ],
//     tableTitle: "Language inventory",
//     table: [
//       ["English", "12,125 books"],
//       ["Bahasa", "6,307 books"],
//       ["Arabic", "5,988 books"],
//       ["Hindi", "3,689 books"],
//       ["Telugu", "3,264 books"],
//       ["Bengali", "1,381 books"],
//       ["Marathi", "664 books"],
//       ["Kannada", "541 books"],
//     ],
//     notes: [
//       "ISBN-attributed structure supports source traceability.",
//       "Text and visuals help models learn context beyond plain text.",
//     ],
//   },
//   {
//     id: "qa",
//     label: "Q&A",
//     title: "6.5M+ questions with explanations",
//     summary:
//       "Reasoning-heavy question-answer data for STEM, non-STEM, multilingual training, evaluation, and instruction tuning.",
//     accent: "from-violet-300/25 to-cyan-400/10",
//     metrics: [
//       ["4M+", "English questions"],
//       ["2.5M+", "Indian language questions"],
//       ["130K+", "Arabic questions"],
//       ["1.8B+", "tokens"],
//       ["210", "words per question"],
//       ["PDF + JSON", "delivery"],
//     ],
//     tableTitle: "Attributes",
//     table: [
//       ["Question", "Prompt body and context"],
//       ["Options", "Multiple-choice candidates where applicable"],
//       ["Answer", "Right answer and answer key"],
//       ["Explanation", "Reasoning path for SFT"],
//       ["Equations", "LaTeX and MathML support"],
//       ["Images", "Interwoven diagrams and visual context"],
//     ],
//     notes: [
//       "Built for STEM and non-STEM coverage.",
//       "Useful for reasoning, benchmark preparation, and model evaluation.",
//     ],
//   },
//   {
//     id: "coding",
//     label: "Coding",
//     title: "11,273 codebases and roughly 1B tokens",
//     summary:
//       "DSA, SQL, machine coding, low-level design, competitive mathematics, and repository-history datasets.",
//     accent: "from-sky-300/25 to-indigo-400/10",
//     metrics: [
//       ["8,453", "DSA codebases"],
//       ["1,291", "SQL codebases"],
//       ["637", "machine coding and LLD"],
//       ["892", "competitive math"],
//       ["6,680", "intermediate codebases"],
//       ["4,593", "expert codebases"],
//     ],
//     tableTitle: "Codebase inventory",
//     table: [
//       ["Data structures and algorithms", "5,024 intermediate + 3,429 expert"],
//       ["SQL and database entry", "759 intermediate + 532 expert"],
//       ["Machine coding and LLD", "376 intermediate + 261 expert"],
//       ["Competitive mathematics", "521 intermediate + 371 expert"],
//     ],
//     notes: [
//       "Supports code generation, repository reasoning, and supervised fine-tuning.",
//       "Includes legacy codebases and full commit history patterns.",
//     ],
//   },
// ];
export const corpusTabs = [
  {
    id: "audio",
    label: "Audio",
    icon: "",
    title: "1.96M+ hours of multilingual audio",
    summary:
      "Call center, podcast, and speech intelligence datasets with premium metadata for gender, age, industry, channel, dialect, and language.",
    accent: "from-cyan-300/30 to-blue-400/10",
    metrics: [
      ["1.91M", "call center hours"],
      ["57K", "podcast hours"],
      ["12", "Podcast languages"],
      ["35+", "more languages"],
      ["4", "audio refining steps"],
      ["Dual", "channel support"],
    ],
    tableTitle: "High-volume coverage",
    table: [
      ["Hindi", "582,745 hrs"],
      ["Bengali", "377,048 hrs"],
      ["Nepali", "235,410 hrs"],
      ["English India", "170,166 hrs"],
      ["English US", "127,536 hrs"],
      ["English UK", "90,334 hrs"],
      ["Assamese", "58,478 hrs"],
      ["Arabic", "24,739 hrs"],
    ],
    notes: [
      "Duplicate asset elimination for uniqueness and consistency.",
      "Low-activity voice removal, PII detection and muting, and background noise cleanup.",
      "Podcast coverage includes Arabic, Bengali, Hindi, Tamil, Telugu, Urdu, Marathi, Gujarati, Kannada, Malayalam, Punjabi, and English.",
    ],
    detail: {
      type: "audio",
      callCenter: {
        title: "Call Center Audio — 40+ Languages",
        badge: "Single + Dual Channel",
        subtitle: "English · Arabic · French · Swahili · Bahasa · Urdu · Portuguese · Kinyarwanda · Luganda · Nepali · Bengali · and 28 more",
        languages: [
          { name: "English (US)", code: "en_US", pct: 22, hrs: "127.5K hrs", dual: true },
          { name: "English (UK)", code: "en_GB", pct: 16, hrs: "90.3K hrs", dual: true },
          { name: "English (India)", code: "en_IN", pct: 29, hrs: "170.2K hrs", dual: true },
          { name: "Arabic", code: "ar_XA", pct: 4, hrs: "25K hrs", dual: true },
          { name: "French", code: "fr_FR", pct: 5, hrs: "30.1K hrs", dual: true },
          { name: "Swahili", code: "sw_KE", pct: 18, hrs: "106.8K hrs", dual: true },
          { name: "Bahasa Indonesia", code: "id_ID", pct: 37, hrs: "216K hrs", dual: true },
          { name: "Punjabi", code: "pa_IN", pct: 5, hrs: "28.3K hrs", dual: true },
          { name: "Marathi", code: "mr_IN", pct: 10, hrs: "41.6K hrs", dual: true },
          { name: "Luganda", code: "lg_UG", pct: 3, hrs: "19.1K hrs", dual: true },
          { name: "Portuguese", code: "pt_BR", pct: 10, hrs: "61K hrs", dual: true },
          { name: "Nepali", code: "ne_NP", pct: 40, hrs: "235.4K hrs", dual: true },
          { name: "Bengali", code: "bn_BD", pct: 65, hrs: "377K hrs", dual: true },
          { name: "+ 28 more languages", code: "", pct: 100, hrs: "Hindi (582.7K), Marathi, Assamese, Odia, Mizo, Chichewa, Ganda, Tamil, Gujarati...", dual: false },
        ],
        industries: ["Banking", "Healthcare", "Insurance", "Agriculture", "Telecom", "QSR", "Logistics", "Humanitarian Aid", "SaaS", "Real Estate"],
        usp: {
          label: "Key USP — Dual Channel",
          text: "Agent and Customer on separate tracks. Gold standard for speaker diarization training. No public dataset matches this at scale.",
        },
      },
      podcast: {
        title: "Podcast Audio — 13 Languages",
        badge: "57,568 Total Hours",
        description: "Natural long-form conversational speech across global and regional languages. Covers Arabic, South Asian, and Southeast Asian languages. Ideal for audio-LLM cross-modal alignment where organic multilingual discourse matters.",
        languages: [
          { name: "Arabic", code: "ar_EG", pct: 52, hrs: "6K hrs" },
          { name: "Urdu", code: "ur_PK", pct: 20, hrs: "2.3K hrs" },
          { name: "Bengali", code: "bn_IN", pct: 67, hrs: "7.8K hrs" },
          { name: "Telugu", code: "te_IN", pct: 51, hrs: "6K hrs" },
          { name: "Punjabi", code: "pa_IN", pct: 42, hrs: "4.8K hrs" },
          { name: "Marathi", code: "mr_IN", pct: 36, hrs: "4.2K hrs" },
          { name: "Kannada", code: "kn_IN", pct: 34, hrs: "4K hrs" },
          { name: "Malayalam", code: "ml_IN", pct: 34, hrs: "4K hrs" },
          { name: "Tamil", code: "ta_IN", pct: 29, hrs: "3.3K hrs" },
          { name: "Gujarati", code: "gu_IN", pct: 21, hrs: "2.5K hrs" },
          { name: "+ 2 more languages", code: "", pct:80 , hrs: "Hindi (11.6K hrs) · English" },
        ],
      },
    },
  },
  {
    id: "video",
    label: "Video",
    icon: "",
    title: "132K+ hours of structured and UGC video",
    summary:
      "STEM classroom and vertical UGC video designed for multimodal grounding, visual reasoning, and cross-modal alignment.",
    accent: "from-emerald-300/25 to-cyan-400/10",
    metrics: [
      ["132K+", "total video hours"],
      ["100K+", "STEM classroom hours"],
      ["30K+", "UGC hours"],
      ["2.2K+", "storytelling hours"],
      ["4.5M", "UGC videos"],
      ["8", "video refining steps"],
    ],
    tableTitle: "Refining process",
    table: [
      ["01", "Duplicate asset elimination"],
      ["02", "Vertical format validation"],
      ["03", "AV1 codec audit"],
      ["04", "Intelligent text recognition"],
      ["05", "Animated content classification"],
      ["06", "AI synthetic media detection"],
      ["07", "Brand logo intelligence"],
      ["08", "Watermark integrity analysis"],
    ],
    notes: [
      "Classroom content is suitable for STEM reasoning and lecture understanding.",
      "Vertical UGC supports short-form visual grounding and noisy real-world formats.",
    ],
    detail: {
      type: "video",
      use: {
        title: "Video Intelligence Corpus",
        badge: "Use-Oriented Mix",
        description:
          "A combined corpus of structured classroom, vertical UGC, and storytelling video for video-language training, visual reasoning, OCR grounding, and real-world multimodal alignment.",
        rows: [
          { source: "Lecture Understanding", volume: "STEM", strength: "Structured teaching, board work, and step-by-step classroom reasoning", pct: 76 },
          { source: "Mobile Scene Grounding", volume: "UGC", strength: "Vertical real-world scenes, short-form behavior, and noisy capture patterns", pct: 23 },
          { source: "Narrative Understanding", volume: "Storytelling", strength: "Temporal flow, event sequencing, and multimodal narrative cues", pct: 42 },
        ],
      },
      pipeline: {
        title: "8-Step Video Refining Process",
        badge: "Quality Gate Stack",
        steps: [
          { n: "01", title: "Duplicate Asset Elimination", note: "Unique asset assurance", pct: 92 },
          { n: "02", title: "Vertical Format Validation", note: "Mobile and portrait compliance check", pct: 88 },
          { n: "03", title: "AV1 Codec Audit", note: "Codec normalization and H.264 standardization", pct: 74 },
          { n: "04", title: "Intelligent Text Recognition", note: "OCR/ITR processing for visible text", pct: 82 },
          { n: "05", title: "Animated Content Classification", note: "Type tagging for motion and animated assets", pct: 68 },
          { n: "06", title: "AI-Synthetic Media Detection", note: "Authenticity filtering before delivery", pct: 79 },
          { n: "07", title: "Brand Logo Intelligence", note: "Logo detection and brand metadata", pct: 62 },
          { n: "08", title: "Watermark Integrity Analysis", note: "Clean output and watermark review", pct: 70 },
        ],
      },
    },
  },
  {
    id: "healthcare",
    label: "Healthcare",
    icon: "",
    title: "53.2M+ healthcare files from verified providers",
    summary:
      "De-identified diagnostic imaging, clinical records, findings, prescriptions, pathology, and longitudinal care datasets.",
    accent: "from-rose-300/25 to-cyan-400/10",
    metrics: [
      ["1.6M+", "patients"],
      ["53M+", "files and images"],
      ["26.8M", "CT images"],
      ["24.8M", "MRI images"],
      ["626K", "X-Ray images"],
      ["376K", "HIV ART records"],
    ],
    tableTitle: "Dataset breakdown",
    table: [
      ["MRI", "77,937 patients + 24,882,631 images"],
      ["CT Scan", "144,847 patients + 26,851,494 images"],
      ["IPD and IVF discharge", "436,801 files"],
      ["Dermatology and OPD", "315,411 images"],
      ["X-Ray", "250,424 patients + 626,954 images"],
      ["USG", "2,974 patients + 9,039 images"],
      ["Pathology", "35,894 files"],
      ["Longitudinal HIV ART", "376,236 files"],
    ],
    notes: [
      "Provider-sourced medical samples are de-identified for privacy.",
      "Clinical validation and standardization support AI readiness.",
    ],
    detail: {
      type: "healthcare",
      radiology: {
        title: "Radiology & Imaging",
        badge: "DICOM + PDF Paired",
        description: "Real Indian hospital data. Available only, reports only (PDF), or paired DICOM+PDF — the gold standard for multimodal medical AI training.",
        rows: [
          { category: "MRI with Findings", modality: "MRI", patients: "40,562", images: "22.6M", format: "DICOM+PDF" },
          { category: "MRI without Findings", modality: "MRI", patients: "10,526", images: "2.3M", format: "DICOM" },
          { category: "MRI Only Findings", modality: "MRI", patients: "26,849", images: "—", format: "PDF" },
          { category: "CT with Findings", modality: "CT", patients: "89,828", images: "20.6M", format: "DICOM+PDF" },
          { category: "CT without Findings", modality: "CT", patients: "25,726", images: "6.2M", format: "DICOM" },
          { category: "X-ray with Findings", modality: "X-ray", patients: "55,403", images: "284,462", format: "DICOM+PDF" },
          { category: "X-ray without Findings", modality: "X-ray", patients: "194,400", images: "341,871", format: "DICOM+JPEG" },
          { category: "USG with Findings", modality: "USG", patients: "776", images: "6,841", format: "DICOM+PDF" },
          { category: "USG Only Findings", modality: "USG", patients: "2,198", images: "—", format: "DOC" },
          { category: "ECHO Only Findings", modality: "ECHO", patients: "104", images: "—", format: "DOC" },
          { category: "OPG X-ray", modality: "OPG", patients: "621", images: "621", format: "JPEG" },
          { category: "Pathology Reports", modality: "Pathology", patients: "35,894", images: "—", format: "PDF" },
        ],
      },
      clinical: {
        title: "Clinical & Specialist Records",
        badge: "1.6M+ Patient Records",
        description: "Longitudinal clinical records are among the rarest assets in medical AI training. InfoBay holds 376K+ HIV ART patients with multi-year treatment timelines and 405K+ IVF procedure records with full clinical context — datasets with no comparable commercial alternative.",
        rows: [
          { category: "IVF Discharge Summary", specialty: "IVF", patients: "405,085", format: "PDF" },
          { category: "Longitudinal HIV ART", specialty: "HIV Therapy", patients: "376,236", format: "CSV" },
          { category: "Dermatology Prescription", specialty: "Dermatology", patients: "267,859", format: "PDF" },
          { category: "Derm + Skin Images", specialty: "Dermatology", patients: "16,038", format: "JPEG+PDF" },
          { category: "OPD Prescription", specialty: "Outpatient", patients: "19,757", format: "PDF+CSV" },
          { category: "IPD Discharge Summary", specialty: "Multi-specialty", patients: "31,716", format: "PDF" },
        ],
        ipdSpecialties: ["Oncology", "General Medicine", "Gastroenterology", "Nephrology", "Cardiology"],
        hivFields: "Demographics · CD4 values · Viral load · Regimen info · Comorbidities · WHO staging · Treatment timeline",
      },
      radTabs: {
        title: "Radiology Disease Classification",
        badge: "Age-Stratified · 5 Age Bands",
        description: "Disease/diagnosis taxonomy across CT, MRI, and X-ray — classified by age group with male/female breakdown. Critical for training age-aware diagnostic AI.",
        ct: {
          label: "CT — Computed Tomography",
          note: "CT disease classifications — patient counts by age group (Under 15 / 15-30 / 30-45 / 45-60 / Over 60)",
          items: [
            { name: "Cerebral Atrophy", count: "2,663" },
            { name: "Acute Infarct + Cerebral Atrophy", count: "90" },
            { name: "Diffuse Disc Bulge", count: "61" },
            { name: "Acute Infarct", count: "73" },
            { name: "Aneurysm", count: "39" },
            { name: "Cerebral Atrophy + Mass Effect", count: "17" },
            { name: "Atrophy + Intracranial Hemorrhage", count: "13" },
            { name: "Atrophy + Mass Effect", count: "13" },
            { name: "Cerebral Atrophy + Hemorrhage", count: "13" },
            { name: "Diffuse Disc Bulge + Lumbar Spondylosis", count: "12" },
            { name: "Cellulitis", count: "11" },
            { name: "Acute Infarct + Atrophy", count: "15" },
            { name: "Cerebral Atrophy + Sinusitis", count: "6" },
            { name: "Atrophy + Hydrocephalus", count: "2" },
            { name: "Atrophy + Encephalomalacia", count: "9" },
            { name: "Cerebral Atrophy + Stroke", count: "2" },
            { name: "Aneurysm + Intracranial Hemorrhage", count: "1" },
            { name: "Acute Infarct + Mass Effect", count: "9" },
          ],
        },
        mri: {
          label: "MRI",
          note: "MRI disease classifications — Brain, Spine, Musculoskeletal, age-stratified",
          items: [
            { name: "Atrophy", count: "1,313" },
            { name: "Acute Infarct + Cerebral Atrophy", count: "182" },
            { name: "Acute Infarct", count: "189" },
            { name: "Acute Infarct + Hemorrhage", count: "192" },
            { name: "Acute Infarct + Atrophy", count: "113" },
            { name: "Atrophy + Hemorrhage", count: "152" },
            { name: "Atrophy + Joint Effusion", count: "111" },
            { name: "Atrophy + Encephalomalacia", count: "53" },
            { name: "Atrophy + Joint Effusion + Marrow Edema", count: "62" },
            { name: "Aneurysm", count: "20" },
            { name: "Acute Infarct + White Matter Hyperintensities", count: "10" },
            { name: "Atrophy + Hydrocephalus", count: "3" },
            { name: "Aneurysm + Atrophy", count: "6" },
            { name: "Aneurysm + Hemorrhage", count: "4" },
            { name: "Atrophy + Inflammation", count: "2" },
            { name: "Aneurysm + Diffuse Disc Bulge", count: "5" },
            { name: "Acute Infarct + Hydrocephalus", count: "11" },
            { name: "Aneurysm + Tumor", count: "4" },
          ],
        },
        xray: {
          label: "X-ray",
          note: "X-ray disease classifications — Chest, Spine, Musculoskeletal, age-stratified",
          items: [
            { name: "Marginal Osteophytes", count: "1,255" },
            { name: "Consolidation", count: "93" },
            { name: "Pleural Effusion", count: "51" },
            { name: "Osteoarthritis Changes", count: "44" },
            { name: "Lumbar Spondylosis", count: "41" },
            { name: "Bronchovascular Marking", count: "34" },
            { name: "Joint Space Narrowing + OA", count: "29" },
            { name: "Cardiomegaly", count: "26" },
            { name: "Compression Fracture + Spondylosis", count: "23" },
            { name: "Compression Fracture", count: "27" },
            { name: "Consolidation + Infiltration", count: "16" },
            { name: "Lytic Lesion", count: "9" },
            { name: "Avulsion Fracture", count: "9" },
            { name: "Consolidation + Pleural Effusion", count: "11" },
            { name: "OA + Subchondral Sclerosis", count: "2" },
            { name: "COPD", count: "2" },
            { name: "Haziness + Pleural Effusion", count: "1" },
            { name: "Marginal Osteophytes + Soft Tissue", count: "9" },
          ],
        },
      },
    },
  },
  {
    id: "textbook",
    label: "Textbook",
    icon: "",
    title: "2.4B+ words from 35,000+ textbooks",
    summary:
      "Licensed textbook corpus spanning 15 languages, 5,000+ subjects, and interwoven visuals for contextual model learning.",
    accent: "from-amber-300/25 to-cyan-400/10",
    metrics: [
      ["35K+", "books"],
      ["2.4B+", "words"],
      ["15", "languages"],
      ["5K+", "subjects"],
      ["12K", "English books"],
      ["6K", "Bahasa books"],
    ],
    tableTitle: "Language inventory",
    table: [
      ["English", "12,125 books"],
      ["Bahasa", "6,307 books"],
      ["Arabic", "5,988 books"],
      ["Hindi", "3,689 books"],
      ["Telugu", "3,264 books"],
      ["Bengali", "1,381 books"],
      ["Marathi", "664 books"],
      ["Kannada", "541 books"],
    ],
    notes: [
      "ISBN-attributed structure supports source traceability.",
      "Text and visuals help models learn context beyond plain text.",
    ],
    // Rich detail data from HTML
    detail: {
      type: "textbook",
      subjectFilters: [
        { label: "All Subjects", value: "all" },
        { label: "Mathematics", value: "Mathematics" },
        { label: "Medical", value: "Medical Science" },
        { label: "Engineering", value: "Engineering" },
        { label: "History", value: "History" },
        { label: "Literature", value: "Literature" },
        { label: "Law", value: "Law" },
        { label: "Economics", value: "Economics" },
      ],
      langFilters: [
        { label: "All Languages", value: "all" },
        { label: "English", value: "en" },
        { label: "Hindi", value: "hi" },
        { label: "Arabic", value: "ar" },
        { label: "Bahasa/Javanese", value: "id" },
        { label: "Telugu", value: "te" },
        { label: "Bengali", value: "bn" },
        { label: "Tamil", value: "ta" },
        { label: "Marathi", value: "mr" },
        { label: "Sanskrit", value: "sa" },
      ],
      books: [
        { cat: "Medical Science", lang: "en", langLabel: "English", type: "STEM", title: "A Contemporary Nursing Process", words: "205M words", pages: "591.3K pp" },
        { cat: "Mathematics", lang: "en", langLabel: "English", type: "STEM", title: "A First Course in Linear Algebra", words: "53.5M words", pages: "169.1K pp" },
        { cat: "History", lang: "en", langLabel: "English", type: "Non-STEM", title: "1965 — A Western Sunrise", words: "44.6M words", pages: "114.6K pp" },
        { cat: "Economics", lang: "en", langLabel: "English", type: "Non-STEM", title: "21st Century Political Science", words: "28.4M words", pages: "84.3K pp" },
        { cat: "Mathematics", lang: "hi", langLabel: "Hindi", type: "STEM", title: "अवकलन (Differentiation)", words: "9.5M words", pages: "27.7K pp" },
        { cat: "History", lang: "hi", langLabel: "Hindi", type: "Non-STEM", title: "1857 का स्वातंत्र्य समर", words: "13.9M words", pages: "32.7K pp" },
        { cat: "Engineering", lang: "ar", langLabel: "Arabic", type: "STEM", title: "ابتكارات الطاقة النظيفة", words: "9.2M words", pages: "52.7K pp" },
        { cat: "Law", lang: "ar", langLabel: "Arabic", type: "Non-STEM", title: "اجتهاد القاضي في غزة", words: "15.5M words", pages: "74.7K pp" },
        { cat: "Mathematics", lang: "te", langLabel: "Telugu", type: "STEM", title: "10వ తరగతి గణితం", words: "4.9M words", pages: "22.7K pp" },
        { cat: "Literature", lang: "bn", langLabel: "Bengali", type: "Non-STEM", title: "10ম শ্রেণী কিশোর উপন্যাস", words: "9.7M words", pages: "36.3K pp" },
        { cat: "Literature", lang: "id", langLabel: "Javanese", type: "Classical", title: "Babad Giyanti — Javanese Chronicle", words: "4.8M words", pages: "12.6K pp" },
        { cat: "Literature", lang: "sa", langLabel: "Sanskrit", type: "Non-STEM", title: "अग्निक्रियातत्त्वचिन्तनम्", words: "0.6M words", pages: "3.8K pp" },
        { cat: "Engineering", lang: "id", langLabel: "Bahasa", type: "STEM", title: "Administrator Jaringan WAN dan Wireless", words: "19.5M words", pages: "109.3K pp" },
        { cat: "Medical Science", lang: "mr", langLabel: "Marathi", type: "STEM", title: "आरोग्य आणि आहारशास्त्र", words: "0.8M words", pages: "2.7K pp" },
      ],
    },
  },
  {
    id: "qa",
    label: "Q&A",
    icon: "",
    title: "6.5M+ human-verified Q&A pairs",
    summary:
      "Reasoning-heavy question-answer data for STEM, non-STEM, multilingual training, evaluation, and instruction tuning.",
    accent: "from-violet-300/25 to-cyan-400/10",
    metrics: [
      ["4M+", "English questions"],
      ["2.5M+", "Indian vernacular"],
      ["130K+", "Arabic questions"],
      ["1.8B+", "tokens"],
      ["210", "words per question"],
      ["PDF + JSON", "delivery"],
    ],
    tableTitle: "Attributes",
    table: [
      ["Question", "Prompt body and context"],
      ["Options", "Multiple-choice candidates where applicable"],
      ["Answer", "Right answer and answer key"],
      ["Explanation", "Reasoning path for SFT"],
      ["Equations", "LaTeX and MathML support"],
      ["Images", "Interwoven diagrams and visual context"],
    ],
    notes: [
      "Built for STEM and non-STEM coverage.",
      "Useful for reasoning, benchmark preparation, and model evaluation.",
    ],
    detail: {
      type: "qa",
      use: {
        title: "Reasoning Q&A Corpus",
        badge: "Training Utility",
        description:
          "Human-verified Q&A pairs with explanations, answer keys, options, equations, and interwoven images for reasoning-heavy SFT, benchmark preparation, and evaluation.",
        rows: [
          { category: "Reasoning SFT", volume: "Instruction", note: "Question, answer, and explanation chains for supervised fine-tuning", pct: 92 },
          { category: "Benchmark Prep", volume: "Evaluation", note: "STEM, non-STEM, and multilingual coverage for test-style assessment", pct: 68 },
          { category: "Multimodal QA", volume: "Grounding", note: "Interwoven diagrams, equations, and visual context for richer understanding", pct: 34 },
          { category: "Structured Delivery", volume: "PDF + JSON", note: "Training-ready exports with answer keys, options, and schema consistency", pct: 85 },
        ],
      },
      schema: {
        title: "Question Object Schema",
        badge: "PDF + JSON",
        fields: [
          { field: "Question", note: "Prompt body, stem, passage, or visual context" },
          { field: "Options", note: "Multiple-choice candidates where applicable" },
          { field: "Right Answer", note: "Answer key for supervised training and evaluation" },
          { field: "Explanation", note: "Reasoning path for SFT and chain-of-thought style learning" },
          { field: "Equations", note: "LaTeX and MathML support for STEM tasks" },
          { field: "Images", note: "Interwoven diagrams and visual references" },
        ],
      },
    },
  },
  {
    id: "coding",
    label: "Coding",
    icon: "",
    title: "12.3K codebases and roughly 1B tokens",
    summary:
      "DSA, SQL, machine coding, low-level design, competitive mathematics, and repository-history datasets.",
    accent: "from-sky-300/25 to-indigo-400/10",
    metrics: [
      ["12K+", "total codebases"],
      ["~1B", "tokens"],
      ["9,453", "DSA codebases"],
      ["1,291", "SQL codebases"],
      ["64K", "Total problems"],
      ["637", "machine coding and LLD"],
    ],
    tableTitle: "Codebase inventory",
    table: [
      ["Data structures and algorithms", "5,024 intermediate + 3,429 expert"],
      ["SQL and database entry", "759 intermediate + 532 expert"],
      ["Machine coding and LLD", "376 intermediate + 261 expert"],
      ["Competitive mathematics", "521 intermediate + 371 expert"],
    ],
    notes: [
      "Supports code generation, repository reasoning, and supervised fine-tuning.",
      "Includes legacy codebases and full commit history patterns.",
    ],
    // Rich detail data from HTML
    detail: {
      type: "coding",
      dsa: {
        title: "Data Structures & Algorithms Corpus",
        badge: "9 Languages · 64,853 Problems",
        description: "Structured DSA problems solved across 13 programming languages. Expert-written, curated — not GitHub-scraped. Same problem available in multiple languages for cross-language parallel training.",
        languages: [
          { lang: "Java", count: "12,256", lines: "800K lines", tokens: "5.1M tokens" },
          { lang: "JavaScript", count: "12,175", lines: "696K lines", tokens: "4.6M tokens" },
          { lang: "C#", count: "12,093", lines: "811K lines", tokens: "5.1M tokens" },
          { lang: "C++", count: "11,866", lines: "739K lines", tokens: "4.7M tokens" },
          { lang: "Python", count: "8,806", lines: "448K lines", tokens: "3M tokens" },
          { lang: "Python 3", count: "3,902", lines: "177K lines", tokens: "1.2M tokens" },
          { lang: "PHP", count: "2,350", lines: "104K lines", tokens: "699K tokens" },
          { lang: "C", count: "818", lines: "44K lines", tokens: "291K tokens" },
        ],
        otherLangs: ["C++14 · 577", 
          // "Dart · 1", "Kotlin · 2", "MATLAB · 1", "Node.js · 6"

        ],
        stats: [
          { value: "64,853", label: "Total DSA Problems" },
          { value: "3.86M", label: "Lines of Code" },
          { value: "25M", label: "Training Tokens" },
        ],
        usp: {
          label: "Key USP vs. The Stack / GitHub Scrapes",
          text: "Same problem in 13 languages = cross-language parallel corpus. Most open-source code datasets are repository-scraped and language-imbalanced. InfoBay's corpus is organized by problem — curated, not scraped.",
        },
      },
    },
  },
];

// export const datasetUsps = [
//   {
//     title: "Audio",
//     stat: "1.96M+ hrs",
//     proof: "PII muting + noise cleanup",
//     points: ["Dual-channel call center depth", "Podcast diversity across 12 languages", "Premium speaker and industry metadata"],
//   },
//   {
//     title: "Video",
//     stat: "4.5M UGC",
//     proof: "8-step video QA",
//     points: ["STEM classroom grounding", "Synthetic media filtering", "OCR and watermark integrity checks"],
//   },
//   {
//     title: "Healthcare",
//     stat: "53M+ files",
//     proof: "De-identified provider data",
//     points: ["MRI, CT, X-Ray, USG, pathology", "Longitudinal HIV and IVF records", "Clinical validation workflows"],
//   },
//   {
//     title: "Textbook",
//     stat: "2.4B+ words",
//     proof: "ISBN traceability",
//     points: ["35,000+ books", "15-language academic corpus", "Text plus visual context"],
//   },
//   {
//     title: "Q&A",
//     stat: "6.5M+ Qs",
//     proof: "Explanations included",
//     points: ["1.8B+ tokens", "LaTeX and MathML support", "PDF and JSON delivery"],
//   },
//   {
//     title: "Coding",
//     stat: "11,273 repos",
//     proof: "Intermediate + expert levels",
//     points: ["DSA, SQL, LLD, system design", "Roughly 1B code tokens", "Repository reasoning ready"],
//   },
// ];
export const uspTabs = [
  {
    id: "audio",
    label: "Audio",
    icon: "🎙️",
    accent: "from-cyan-500/20 to-blue-500/10",
    tag: "cyan",
    usps: [
      {
        n: "USP 01",
        title: "Real Spontaneous Speech — Not Scripted",
        body: "Live call center conversations capture disfluencies, interruptions, code-switching, and domain vocabulary used organically. Models trained on real conversations generalize far better to production than prompted audio.",
        proof: "vs. acted / prompted: more realistic acoustic and lexical variation",
      },
      {
        n: "USP 02",
        title: "Dual Channel — Agent & Customer Separate Tracks",
        body: "Perfect diarization ground truth without post-hoc separation. Unlocks contact center AI, agent assist, compliance monitoring. Available for English (US/UK/IN), French, Arabic, Nepali, Bengali, Swahili, and more.",
        proof: "Gold standard for speaker diarization — no public dataset matches this at scale",
      },
      {
        n: "USP 03",
        title: "15+ Industry Verticals — Native Domain Vocabulary",
        body: "Banking, healthcare, insurance, agriculture, telecom, QSR, humanitarian aid, SaaS, real estate, solar energy, travel. Industry-specific vocabulary inherent in the data — not annotated after the fact.",
        proof: "Industries: Banking · Healthcare · Insurance · Agriculture · Telecom · QSR · SaaS · Logistics · Humanitarian Aid · Real Estate",
      },
      {
        n: "USP 04",
        title: "Low-Resource Global Languages Unavailable Elsewhere",
        body: "African languages: Swahili (18,031 hrs), Kinyarwanda (3,287 hrs), Luganda (16,067 hrs), Ganda, Chichewa. South Asian: Nepali (235K hrs), Bengali (377K hrs), Odia (12.7K hrs). Southeast Asian: Bahasa Indonesia, Javanese. All with enterprise-grade quality annotation and dual-channel where available.",
        proof: "Swahili 18,031 hrs · Nepali 235K hrs · Kinyarwanda 3,287 hrs · no commercial alternative at this depth",
      },
      {
        n: "USP 05",
        title: "Multilingual Code-Switching — Natural, Not Scripted",
        body: "Real-world multilingual environments naturally blend languages within conversations — Arabic-French in North Africa, Bahasa-English across Southeast Asia, English-local language in enterprise call centers globally. InfoBay's corpus captures this cross-lingual mixing organically at scale, enabling voice AI models that handle real-world multilingual conversation without brittle hard language boundaries.",
        proof: "No synthetic or scripted dataset replicates the natural code-switching patterns found in real enterprise call centers",
      },
      {
        n: "USP 06",
        title: "Enterprise Data Agreements — Consent-Chain Documented",
        body: "Collected via formal agreements with enterprise operators. EU AI Act Article 10, India DPDP Act, and CCPA require documented provenance. InfoBay's collection architecture is built for this from the ground up.",
        proof: "Not web-scraped · GDPR-eligible lineage · enterprise agreement structure",
      },
    ],
  },
  {
    id: "textbook",
    label: "Textbook",
    icon: "📚",
    accent: "from-amber-500/20 to-yellow-500/10",
    tag: "amber",
    usps: [
      {
        n: "USP 01",
        title: "Published Academic Content — Educational Quality by Design",
        body: "FineWeb-Edu proved educational text improves ARC by +24% and MMLU by +12% by filtering 90% of CommonCrawl. InfoBay's textbooks achieve that quality without filtering — published, peer-reviewed, zero aggressive filtering needed.",
        proof: "FineWeb removes 90% of tokens to reach educational quality. InfoBay textbooks: 0% removal needed.",
      },
      {
        n: "USP 02",
        title: "ISBN-Level Provenance — Every Book Attributed",
        body: "Complete provenance chain from token to published source. EU AI Act Article 10 compliance-ready. AllenAI Dolma provides sub-corpus provenance. InfoBay provides book-level ISBN attribution — the granularity difference matters for legal review.",
        proof: "EU AI Act Article 10: High-risk AI must document training data sources. ISBN = compliance-ready.",
      },
      {
        n: "USP 03",
        title: "16 Languages · 7 Writing Systems — Including Sanskrit and Javanese",
        body: "Sanskrit Non-STEM books may be unique globally as a commercial training corpus. Javanese classical chronicles (Babad texts, 100M+ speakers) are equally rare. Arabic/Urdu STEM textbooks cover domains almost entirely absent from RTL web corpora.",
        proof: "Scripts: Latin · Devanagari · Arabic · Bengali · Telugu · Kannada · Tamil · Gurmukhi · Malayalam",
      },
      {
        n: "USP 04",
        title: "STEM + Non-STEM Dual Taxonomy — 50+ Categories",
        body: "15+ STEM categories in 11 languages. 30+ Non-STEM categories (Law, History, Literature, Economics, Psychology, Business, Political Science, Linguistics, Philosophy, Religion) in 15 languages. Enables precise training domain mixing ratios.",
        proof: "No open dataset covers this multilingual humanities breadth with publisher-attributed provenance",
      },
      {
        n: "USP 05",
        title: "Word Count + Page Count Metadata Per Book",
        body: "Token estimation immediate without preprocessing: ~1.3 tokens/word Indic, ~0.75 English. Per-book category tags enable programmatic data mixing strategies. This is the data card information ML teams request first.",
        proof: "Example: Textbook of Agronomy = 48.2M words · 176K pp. Political Science = 55.1M words · 177K pp.",
      },
    ],
  },
  {
    id: "healthcare",
    label: "Healthcare",
    icon: "🩺",
    accent: "from-rose-500/20 to-pink-500/10",
    tag: "rose",
    usps: [
      {
        n: "USP 01",
        title: "Multimodal Paired DICOM + PDF — Gold Standard for Medical AI",
        body: "77,937 MRI patients and 144,847 CT patients with both raw DICOM images AND corresponding PDF radiologist reports. Most public medical datasets provide images or reports — not both from the same encounter. Paired structure is essential for vision-language models and radiology AI.",
        proof: "MRI paired: 24.8M images + 37K reports · CT paired: 26.8M images + 30K reports",
      },
      {
        n: "USP 02",
        title: "Real Indian Hospital Data — Underrepresented Demographics",
        body: "South Asian patient demographics are severely underrepresented in global medical AI training (most datasets are US/European). Models trained on Western radiology data perform worse on Indian populations due to differences in disease prevalence, body composition, and presentation patterns.",
        proof: "Unique: tropical diseases, distinct BMI distributions, South Asian neurological presentations",
      },
      {
        n: "USP 03",
        title: "Age-Stratified Disease Taxonomy Across CT, MRI, and X-ray",
        body: "Patient counts per disease across 5 age bands (Under 15, 15–30, 30–45, 45–60, Over 60) with male/female breakdown. Enables training of age-aware diagnostic models — a capability no public dataset provides at this specificity for Indian populations.",
        proof: "CT: 100+ disease categories · MRI: 100+ · X-ray: 60+ — all age-stratified with gender breakdown",
      },
      {
        n: "USP 04",
        title: "Longitudinal HIV ART (376K) + IVF (405K) — Treatment Timeline Data",
        body: "Longitudinal clinical data for treatment response prediction is exceptionally rare at scale for South Asian populations. HIV ART fields: CD4 values, viral load, regimen information, comorbidities, WHO staging across time. IVF: procedure details, anaesthesia, and findings across 405K patients.",
        proof: "HIV ART fields: CD4 · VL · regimen info · comorbidities · WHO staging · demographics",
      },
      {
        n: "USP 05",
        title: "20 Medical Specialties — Breadth for General Medical AI",
        body: "MRI · CT · X-ray · OPG · USG · ECHO · Pathology · Dermatology · IVF · HIV/Infectious Disease · Oncology · Cardiology · Gastroenterology · Nephrology · General Medicine · Outpatient. This breadth is what general-purpose medical AI models require.",
        proof: "1.6M+ patient records · 53M+ images · 20 specialties · real clinical fields throughout",
      },
    ],
  },
  {
    id: "coding",
    label: "Coding",
    icon: "💻",
    accent: "from-indigo-500/20 to-sky-500/10",
    tag: "indigo",
    usps: [
      {
        n: "USP 01",
        title: "Cross-Language Parallel Corpus — Same Problem in 13 Languages",
        body: "The same DSA problem solved in Java, C++, Python, JavaScript, C#, PHP, C, and more. This structure enables training of models that translate between languages, explain code across paradigms, and understand algorithmic equivalence. Most open-source datasets are scraped and language-imbalanced.",
        proof: "64,853 problems × up to 9 languages = structured cross-language corpus unlike any public alternative",
      },
      {
        n: "USP 02",
        title: "DSA Focus — Reasoning-Intensive Code That Improves Model Intelligence",
        body: "DSA problems require explicit reasoning: problem decomposition, algorithm selection, complexity analysis, edge case handling. Training on DSA content improves reasoning capabilities beyond coding tasks — analogous to how STEM textbooks improve general reasoning benchmarks.",
        proof: "DSA covers: Sorting · Graphs · Dynamic programming · Trees · Recursion · Hashing · Greedy · Divide & conquer",
      },
      {
        n: "USP 03",
        title: "25M Tokens — Substantial Scale for Fine-Tuning",
        body: "25.02M total tokens across 9 languages. Sufficient for domain-specific fine-tuning of code LLMs (CodeLLaMA, StarCoder, DeepSeek-Coder) on algorithmic problem-solving. Java alone: 5.15M tokens. C#: 5.1M. JavaScript: 4.55M. C++: 4.72M.",
        proof: "Java: 5.15M tokens · C#: 5.1M · C++: 4.72M · JavaScript: 4.55M · Python: 3.04M",
      },
      {
        n: "USP 04",
        title: "Curated & Problem-Organized — Not Web-Scraped GitHub",
        body: "Unlike The Stack (6.4TB of GitHub scrapes), InfoBay's coding corpus is organized by problem — not by repository. Each problem is a discrete, verified unit with a known algorithmic category. Enables precise fine-tuning on specific algorithm families and controlled evaluation.",
        proof: "vs. The Stack: repository-scraped, imbalanced. InfoBay: problem-organized, cross-language, DSA-focused.",
      },
    ],
  },
];


export const capabilities = [
  ["Pre-Training Curation", "ISBN-attributed textbooks · 15 languages · deduplicated · not web-scraped. FineWeb-Edu achieved +24% ARC from educational text — ours comes from actual published books."],
  ["SFT Dataset Design", "Instruction datasets with explicit reasoning traces. Built by domain SMEs — attorneys, physicians, researchers, engineers — not crowdworkers. Chain-of-thought citations included."],
  ["RLHF & Reward Modeling", "1.96M+ hours of real industry audio · dual-channel · 40+ languages · WER-tracked. Speaker-disjoint splits. The signal that makes reward models calibrate correctly."],
  ["Medical AI Training Data", "53M+ DICOM images paired with radiology reports · 1.6M+ patient records · age-stratified disease taxonomy · 20 specialties · real Indian hospital data."],
  ["Code & Reasoning Datasets", "64K+ DSA problems · 9 languages · 25M tokens · cross-language parallel structure. Same problem in Java, Python, C++, JavaScript, and C# — curated, not scraped."],
  ["The InfoBay Corpus", "Audio · Textbooks · Healthcare · Coding. Four proprietary corpus collections across 40+ languages, 20 medical specialties, and 9 programming languages. Expert-curated. Enterprise-licensed. Training-ready."],
];

export const whyItems = [
  ["A corpus that compounds — not a project that concludes.", "InfoBay's 1.96M+ audio hours, 1.6M+ patient records, 15-language textbook library, and 64K+ coding problems accumulated over years of production engagements. Every project adds to a retained, quality-scored asset no competitor can replicate quickly. When you engage InfoBay, you start from millions of verified examples in your domain — not from zero.", "vs. Scale AI (Meta-controlled, ~10% error rate) · vs. Innodata (synthetic-only) · vs. Surge AI (zero corpus visibility)"],
  ["Epistemic provenance — every training example traceable to its source.", "Every textbook carries its ISBN. Every audio hour carries its language code, industry vertical, channel type. Every medical record carries its modality, specialty, and clinical fields. Every code problem carries its language and algorithmic category. Traceability is not a compliance feature — it is the mechanism that makes training data trustworthy at the root.", "EU AI Act Article 10: High-risk AI must document training data sources. InfoBay's corpus is built for this."],
  ["Outcomes measured in model behavior — not delivery volume.", "We measure success in benchmark deltas, factuality improvement percentages, and evaluation pass rates. FineWeb-Edu demonstrated educational text improves ARC by 24% and MMLU by 12% over web text. Our textbooks achieve that quality without filtering. Our audio provides real-world grounding no open dataset matches. Our medical data is the only Indian hospital corpus with paired DICOM+PDF at this volume.", "FineWeb-Edu NeurIPS 2024: educational text -> +24% ARC, +12% MMLU. InfoBay textbooks: educational by source."],
  // ["Global delivery", "Distributed centers support multilingual, round-the-clock data production for demanding enterprise timelines."],
];
// export const whyItems = [
//   ["Production scale", "20B+ tokens, 57+ languages, 5 major data domains, and continuously updated multimodal datasets."],
//   ["Frontier relevance", "Built for pre-training, supervised fine-tuning, RLHF, reasoning, evaluation, and enterprise AI procurement workflows."],
//   ["Quality operations", "Explicit refinement pipelines across every modality, from duplicate elimination to PII safety and metadata enrichment."],
//   ["Global delivery", "Distributed centers support multilingual, round-the-clock data production for demanding enterprise timelines."],
// ];

export const useCases = [
  ["Chain-of-Thought SFT & Pre-Training", "STEM textbooks across mathematics, medical science, and engineering provide structured reasoning chains that improve ARC and MMLU benchmarks. DSA coding corpus adds algorithmic reasoning depth.", "Reasoning Models", "Corpus: STEM textbooks · 15 languages · Coding · 9 languages · 64K+ DSA problems"],
  ["Domain-Accurate Fine-Tuning", "Law, finance, healthcare, and engineering textbooks provide factual grounding for copilots operating on regulated content — ISBN-attributed, not web-scraped. Expert SME preference annotation for RLHF calibration.", "Enterprise Copilots", "Corpus: Non-STEM textbooks · Law, Business, Healthcare · 15 languages"],
  ["ASR, Speaker Diarization, Conversational AI", "1.9M+ hours of real industry call center audio — dual-channel, 40+ languages, 15 industry verticals. 538K+ hours in South Asian languages, 235K+ Nepali, 106.8K+ Swahili, and coverage across African, Southeast Asian, and European languages. No public dataset approaches this combination.", "Multilingual Voice AI", "Corpus: Call center audio · 40+ languages · English · Arabic · French · Swahili · Nepali · Bengali · Dual channel · 15 verticals"],
  ["Radiology AI, Clinical NLP, Diagnostic Models", "53M+ Indian hospital DICOM images paired with radiologist reports. Age-stratified disease taxonomy for CT, MRI, X-ray. Dermatology image-prescription pairs. Longitudinal HIV ART and IVF data. The infrastructure for AI across South Asian patient populations.", "Medical AI", "Corpus: Healthcare · 1.6M+ patients · 53M+ images · 20 specialties · DICOM+PDF paired"],
  ["Cross-Language Models and Algorithm-Aware Copilots", "64K DSA problems in 9 languages. Same problem available across Java, C++, Python, JavaScript, C#, PHP, and C — not GitHub-scraped. Organized by problem, enabling precise fine-tuning on algorithmic reasoning.", "Code Generation", "Corpus: Coding · 9 languages · 64K+ problems · 25M tokens · cross-language parallel"],
  ["RLHF, Red-Teaming, Refusal Calibration", "Human preference annotation by domain experts — attorneys ranking legal AI outputs, physicians ranking clinical responses. Expert preference data provides the calibration quality commodity RLHF cannot replicate.", "Model Safety & Alignment", "Corpus: Expert annotation · Legal, Medical, Financial domains · Cross-lingual alignment"],
];
// export const useCases = [
//   ["Pre-training enrichment", "Expand model coverage with multilingual audio, textbook, healthcare, video, Q&A, and code corpora."],
//   ["Supervised fine-tuning", "Align domain behavior using curated Q&A, code, medical, educational, and enterprise interaction datasets."],
//   ["RLHF and human evaluation", "Collect expert feedback, safety reviews, preference data, and output evaluations across modalities."],
//   ["Multimodal grounding", "Train systems that connect speech, video, text, images, equations, clinical files, and structured metadata."],
// ];

export const globalCenters = [
  ["Lucknow", "India", "Headquarter"],
  ["Cairo", "Egypt", "Capability Center"],
  ["Jakarta", "Indonesia", "Capability Center"],
  ["Manila", "Philippines", "Capability Center"],
  ["Abu Dhabi", "UAE", "Capability Center"],
  ["Kampala", "Uganda", "Capability Center"],
  ["Nairobi", "Kenya", "Capability Center"],
  ["Kathmandu", "Nepal", "Capability Center"],
];

export const clientLogos = [
  ["/microsoft.png", "Microsoft"],
  ["/meta.png", "Meta"],
  ["/google.png", "Google"],
  ["/amazon.png", "Amazon"],
  ["/lg.png", "LG"],
  ["/alibaba.png", "Alibaba"],
];

export const faqs = [
  ["Can we license specific language subsets or domain slices?", "Yes. The corpus is structured by language, domain, and category — licenses can be scoped to Arabic + Legal, Bahasa + Engineering, or any combination. Minimum license volumes apply. Contact us to discuss your specific requirements."],
  ["How do you handle PII in healthcare and audio datasets?", "Automated PII detection runs across all datasets before delivery. Audio uses speaker anonymisation. Healthcare records have patient identifiers removed at the source. Data lineage documentation available for HIPAA, GDPR, and EU AI Act compliance review."],
  ["Do you offer sample packs before full licensing?", "Yes. 10% sample packs are available for textbooks (per language group) and coding. Audio samples available for specific language-industry combinations. Healthcare samples available under NDA with IRB-equivalent institutional review. Request via the audit form."],
  ["Can you build custom datasets we don't see here?", "Yes. Custom corpus collection, annotation, and curation for domains or languages not in the standard catalogue. Minimum engagement sizes apply. Lead time depends on language, domain, and volume. The Model Quality Audit is the starting point for custom engagements."],
  ["What delivery formats are supported?", "Audio: WAV/FLAC + JSON transcripts + RTTM diarisation + Metadata CSV. Textbooks: JSONL (gzip) + Parquet metadata manifest + HuggingFace-compatible. Healthcare: DICOM + PDF + anonymised metadata. Coding: JSONL per language + problem taxonomy JSON. All formats compatible with Megatron-LM, NeMo, LLaMA-Factory, and HuggingFace datasets."],
  ["How do you document data provenance for AI Act compliance?", "Every textbook carries its ISBN. Every audio hour carries its enterprise data agreement reference, language code, industry vertical, and channel configuration. Every medical record carries its institutional source and modality. Data Cards delivered with every dataset include provenance documentation in the EU AI Act Article 10 format."],
];
