import React from "react";

const TermsOfService = () => {
  return (
    <main className="min-h-screen bg-black text-white pt-20 md:pt-24 pb-12 md:pb-16 px-4 md:px-6">
      <div className="mx-auto max-w-4xl">

        <h1 className="text-2xl sm:text-3xl md:text-4xl font-semibold tracking-tight">
          Understanding Your Rights and Responsibilities as an InfoBay AI User
        </h1>

        {/* 1. Terms of Use */}
        <h2 className="mt-8 md:mt-10 text-base md:text-lg lg:text-xl font-semibold tracking-tight">
          1. Terms of Use
        </h2>

        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          This document is an electronic record generated by a computer system and does not require any physical or digital signatures.
        </p>

        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          Welcome to InfoBay AI, a reliable data partner supporting large language models (LLMs) and hyperscale computing platforms.
        </p>

        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          By electronically executing a Service Order and by accessing or using the Company's website, mobile applications, and related services (collectively referred to as the "Platform") and the services provided through it (the "Services"), you ("Customer", "You", or "Your") agree to these Terms of Service ("ToS") and enter into a legally binding agreement with InfoBay AI.
        </p>

        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          These Terms of Use govern your access to and use of the Platform and Services. By accessing or using the Platform, you agree to comply with and be bound by these Terms, as well as all applicable laws and regulations. If you do not agree with these Terms, you must not access or use the Platform or Services.
        </p>

        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          These Terms incorporate by reference the <b>InfoBay AI Privacy Statement</b>, which forms an integral part of these Terms. By accessing or using the Platform, you acknowledge that you have read, understood, and agree to be bound by these Terms, including the Privacy Statement.
        </p>

        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          The terms "User" and "You" refer to any individual or entity accessing or using the Platform for any purpose.
        </p>

        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          InfoBay AI reserves the right to modify or update these Terms at any time by posting the revised version on this webpage. Users are encouraged to review these Terms periodically, as continued use of the Platform after such updates constitutes acceptance of the revised Terms.
        </p>

        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          Any violation of these Terms may result in suspension or termination of access to the Platform or Services, at the sole discretion of InfoBay AI.
        </p>

        {/* 2. Acceptance of Terms */}
        <h2 className="mt-8 md:mt-10 text-base md:text-lg lg:text-xl font-semibold tracking-tight">
          2. Acceptance of Terms
        </h2>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          Please read these Terms carefully. If you do not agree with any part of these Terms, do not access or use the Platform. Your continued use of the Platform constitutes your acceptance and agreement to comply with these Terms.
        </p>

        {/* 3. Definitions */}
        <h2 className="mt-8 md:mt-10 text-base md:text-lg lg:text-xl font-semibold tracking-tight">
          3. Definitions
        </h2>
        <ul className="list-disc ml-6 mt-3 text-sm md:text-base text-zinc-300 leading-relaxed space-y-1">
          <li><strong>"You" or "User"</strong> – Any individual or entity accessing or using the Platform for any purpose.</li>
          <li><strong>"Platform"</strong> – The InfoBay.ai website, mobile applications, and any services, content, or study materials provided therein.</li>
        </ul>

        {/* 4. Services */}
        <h2 className="mt-8 md:mt-10 text-base md:text-lg lg:text-xl font-semibold tracking-tight">
          4. Services
        </h2>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          <strong>4.1</strong> The Company shall provide You the Services in accordance with the terms and conditions specified here and the Service Order. In the event of conflict between the terms/provisions of this Terms of Service and the respective Service Order (including any exhibits or attachments thereto), the terms of the Service Order, as maybe applicable, shall prevail, but only as regard to that respective Service Order.
        </p>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          <strong>4.2</strong> The Company shall provide the Customer a limited, non-exclusive, non-transferrable, non-sublicensable, non-assignable, revocable right to use and access the Services basis the terms and conditions specified herein and the Service Order.
        </p>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          <strong>4.3</strong> Subject to the ToS and the Service Order, the Company will provide Customer the Services and technical support in accordance with the Service level terms provided herein or as may be provided under one or more Service Orders.
        </p>

        {/* 5. Termination */}
        <h2 className="mt-8 md:mt-10 text-base md:text-lg lg:text-xl font-semibold tracking-tight">
          5. Termination
        </h2>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          <strong>5.1 Termination for convenience:</strong> The Parties may terminate the Service Order for convenience by providing a 30 (Thirty) days prior notice to the other party. In case the Customer terminates the Service Order for convenience it shall be liable to pay the Company the Fees due for the remaining period of the Term.
        </p>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          <strong>5.2 Termination for breach:</strong> Either Party may terminate the Service Order in the event of a material breach by the other Party, provided such breach is not cured by the relevant Party within a period of thirty (30) days of being notified of such breach.
        </p>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          <strong>5.3 Termination for liquidation or insolvency:</strong> Either Party may terminate the Service Order forthwith in any of the following circumstances: a.) if a Party is sought to be wound up or liquidated or any petition for winding up or liquidation has been admitted against a Party, or a Party has resolved through a resolution passed by the board of directors or its shareholders otherwise to wind up voluntarily; or b.) Where the business or assets of a Party are confiscated or seized as a result of governmental interference or if the Customer makes any assignment for benefit of its creditors; or c.) If a Party is declared bankrupt or if any distress or attachment is levied or any receiver is appointed in respect of the business or assets of a Party or if it takes any similar action in consequence of debt.
        </p>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          <strong>5.4 Effects of Termination:</strong> Upon any termination of the Service Order: a.) each Party shall return and make no further use of any equipment, property, materials and other items (and all copies of them) belonging to the other Party; b.) any rights, remedies, obligations or liabilities of the Parties that have accrued up to the date of termination, including the right to claim damages in respect of any breach of the Service Order which existed at or before the date of termination shall not be affected or prejudiced; c.) in case of termination of the Service Order without cause by the Customer, the Company shall not be obligated to return the fees paid by the Customer till the date of termination of the Service Order.
        </p>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          <strong>5.5</strong> Notwithstanding any termination or suspension, Parties shall not be released from or relieved of any claim of any nature or kind whatsoever, which one may have against the other, under or arising out of the Service Order or the ToS.
        </p>

        {/* 6. Modifications */}
        <h2 className="mt-8 md:mt-10 text-base md:text-lg lg:text-xl font-semibold tracking-tight">
          6. Modifications
        </h2>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          InfoBay AI reserves the right to update, revise, or modify these Terms at any time by posting the updated version on this webpage. Users are responsible for periodically reviewing this page. The most current version of the Terms will be binding upon you.
        </p>

        {/* 7. Acceptable Use of Services */}
        <h2 className="mt-8 md:mt-10 text-base md:text-lg lg:text-xl font-semibold tracking-tight">
          7. Acceptable Use of Services
        </h2>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          <strong>7.1 General restrictions:</strong> Customer will not (and will not permit any third party to): (a) rent, lease, provide access to, resell, or sublicense the Services to a third party or provide the Services to a third party as a managed service; (b) use the Services to provide, or incorporate the Services into, any product or service provided to a third party; (c) reverse engineer, decompile, disassemble, or otherwise seek to obtain the source code, except to the extent expressly permitted by applicable law (and then only upon advance notice to the Company); (d) copy or modify the Services or any part thereof, or create any derivative work from any of the foregoing; (e) remove or obscure any proprietary or other notices contained in the Services (including any reports or data printed from the Services); (f) publicly disseminate information regarding the performance of the Services; (g) use the Company Platform and the Services for the purpose of distributing unsolicited communications or messages.
        </p>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          <strong>7.2 Authorised Users:</strong> The Company will provide the Customer and its Authorized Users with Access Credentials to access and use the Company Platform, and hereby agrees and acknowledges that only the Authorized Users shall use and access the Company Platform only by using the Access Credentials. It is the responsibility and obligation of the Customer to safeguard the Access Credentials and not allow any third party to access and use the Company Platform.
        </p>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          <strong>7.3 General obligations:</strong> The Customer shall (a) comply with all Applicable Laws in connection with its use of the Company the Services and of Customer Data including those laws related to data privacy; (b) not upload, post, reproduce or distribute any information, software or other material protected by copyright, privacy rights, or any other Intellectual Property Right without first obtaining the permission of the owner of such information; (c) ensure that Customer Data does not include any viruses, malware, or any other similar harmful content; (d) ensure that valid Customer API(s) are available at all times for the Company to use and access for the purpose of providing the Services including but not limited to receive Customer Data from the Customer Platform. For the foregoing, the Customer grants the Company a limited, non-transferable, non-exclusive right to use Customer API(s) for the purpose of providing Services; (e) provide the Company with all necessary co-operation and information required by the Company to fulfill its obligations including but not limited to completing the integration of Company Platform with Customer Platform.
        </p>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          <strong>7.4 Modification to Services:</strong> The Company reserves all the rights to modify and alter the Services and the Company Platform at its discretion. The Company will ensure that such modification will not directly or indirectly hinder or adversely affect the Services being provided by the Company.
        </p>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          <strong>7.5 Third-party use:</strong> The Company shall not be responsible for any defect or error (i) occurring due to reasons which are not under control of the Company and (ii) not reported to the Company or for any defect or error in the Company's Platform due to modification or misuse of the Company's Platform by the Customer and/or its Authorized Users and/or its third parties who get access to the Company's Platform via the Customer. Further, in the event the Services are integrated with any third-party platforms or software by the Customer by the Company upon the request of the Customer including but not limited to any social media platforms/interactive platforms which shall be subjected to terms and conditions of such third-party platforms, to be complied by the Customer, in such cases, the Company shall not be liable if such third party platform restricts integration or adversely affects the performance, uptime and efficiency of the Services.
        </p>

        {/* 8. Purpose of the Platform */}
        <h2 className="mt-8 md:mt-10 text-base md:text-lg lg:text-xl font-semibold tracking-tight">
          8. Purpose of the Platform
        </h2>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          By using InfoBay AI, you acknowledge and agree that the Platform and its services are provided to support the Company's large language models (LLMs) and hyperscale computing platforms. The Platform is intended to facilitate the development, deployment, and operation of AI-powered tools, data processing, and related technologies in accordance with the Company's policies and applicable laws.
        </p>

        {/* 9. User Obligations and Restrictions */}
        <h2 className="mt-8 md:mt-10 text-base md:text-lg lg:text-xl font-semibold tracking-tight">
          9. User Obligations and Restrictions
        </h2>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          By accessing or using the InfoBay AI Platform ("Platform"), you agree to comply with the following obligations and restrictions:
        </p>
        <p className="mt-4 text-sm md:text-base text-zinc-300 leading-relaxed font-medium">
          User Obligations
        </p>
        <p className="mt-2 text-sm md:text-base text-zinc-300 leading-relaxed">
          You agree to:
        </p>
        <ul className="list-disc ml-6 mt-3 text-sm md:text-base text-zinc-300 leading-relaxed space-y-1">
          <li>Provide accurate, complete, and up-to-date information when registering for or interacting with the Platform.</li>
          <li>Use the Platform only for lawful purposes and in a manner consistent with the educational, technological, and consultancy objectives of InfoBay AI.</li>
          <li>Refrain from reproducing, distributing, modifying, transmitting, or creating derivative works from any Platform content without the prior written consent of InfoBay AI.</li>
          <li>Respect the intellectual property rights, privacy rights, and other legal rights of InfoBay AI and third parties.</li>
          <li>Not attempt to gain unauthorized access to, interfere with, or disrupt the Platform's systems, networks, servers, or data.</li>
          <li>Comply with all applicable local, national, and international laws and regulations while using the Platform.</li>
        </ul>

        {/* 10. Prohibited Activities */}
        <h2 className="mt-8 md:mt-10 text-base md:text-lg lg:text-xl font-semibold tracking-tight">
          10. Prohibited Activities
        </h2>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          Users must not engage in any activities that may harm the Platform, its users, or its operations, including but not limited to:
        </p>
        <ul className="list-disc ml-6 mt-3 text-sm md:text-base text-zinc-300 leading-relaxed space-y-1">
          <li>Using the Platform for fraudulent, deceptive, phishing, spamming, or otherwise unlawful activities.</li>
          <li>Accessing, copying, or sharing confidential or restricted content that is not intended for public use.</li>
          <li>Engaging in harassment, abusive conduct, or any behavior that infringes upon the rights of others, including intellectual property, privacy, or contractual rights.</li>
        </ul>

        {/* 11. Customer Data */}
        <h2 className="mt-8 md:mt-10 text-base md:text-lg lg:text-xl font-semibold tracking-tight">
          11. Customer Data
        </h2>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          <strong>11.1</strong> The Customer grants the Company a limited, worldwide, non-transferable, non-exclusive, non-sublicensable, royalty-free right to use and process the Customer Data, during the Term solely to the extent required to enable the Company to provide the Services to the Customer. Notwithstanding anything to the contrary, Company may collect, aggregate and analyze the Company Data to improve and enhance the Services.
        </p>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          <strong>11.2</strong> The Customer shall be solely liable for (i) the accuracy, quality, content, legality and use of Customer Data, including the means by which the Customer has acquired, collected and transferred such Customer Data; (ii) compliance with any Applicable Law (including applicable data protection and intellectual property rights); (iii) obtaining necessary consent from the End User for the purpose of Company using the End User data for the provision of the Services. Customer shall ensure that the Customer has provided for prominent notice of use of the data of such End User for Services and has made reasonable efforts that their End User has reviewed their privacy policy.
        </p>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          <strong>11.3</strong> The Company will use reasonable efforts to maintain the privacy and confidentiality of the Customer Data and will put in place reasonable safeguard and system for the same including physical, technical, administrative, and organizational safeguards and in doing so, shall observe compliance with Applicable Laws, including applicable data privacy laws.
        </p>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          <strong>11.4</strong> The Customer acknowledges that the Company exercises no control or verifies, the content of the information transmitted by Customer or Customer Data.
        </p>

        {/* 12. Indemnification and Limitation of Liability */}
        <h2 className="mt-8 md:mt-10 text-base md:text-lg lg:text-xl font-semibold tracking-tight">
          12. Indemnification and Limitation of Liability
        </h2>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          <strong>12.1 Customer Indemnification.</strong> The Customer shall indemnify and hold harmless the Company, its officers, directors, agents and employees from all direct liabilities against and in respect of any loss, claims, costs, damages, expenses, obligations, liabilities, actions, suits, including reasonable attorneys' fees and costs and all amounts paid in settlement of any claim resulting from or relating to any breach by Customer (i) of clause 7 (Acceptable Use of Services) and any liability arising due to Customer Data; (ii) harm to Services due to third-party platforms integrated on Customer's request; (iii) liability arising from End-User claims against the Company, due to Customer's acts or omissions.
        </p>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          <strong>12.3</strong> Notwithstanding anything stated herein, neither Party will be liable to the other, for any incidental, consequential, penal or indirect damages (including for loss of business, profits or Customer Data) even if advised of the possibility of the same. The aggregate liability of the Parties arising under this ToS or the Service Order shall be limited to the Fees payable or received by the Company from the Customer for the Services for in the 12 (Twelve) months immediately preceding the relevant Party's notice of such claim.
        </p>

        {/* 13. Representation and Warranties */}
        <h2 className="mt-8 md:mt-10 text-base md:text-lg lg:text-xl font-semibold tracking-tight">
          13. Representation and Warranties
        </h2>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          Each Party hereunder represents and warrants to the other Party as follows:
        </p>
        <ul className="list-disc ml-6 mt-3 text-sm md:text-base text-zinc-300 leading-relaxed space-y-2">
          <li>(a) It has the full right and legal authority to enter into and fully perform in accordance with its terms;</li>
          <li>(b) The Service Order, when executed and delivered by such Party, will be its respective legal, valid and binding obligation enforceable against it in accordance with its terms;</li>
          <li>(c) The execution and delivery of Service Order have been duly authorized by such Party, and such execution and delivery and the performance by each Party of its respective obligations hereunder, do not and will not violate or cause a breach of any agreement or other obligation to which it is a Party or by which it is bound or affected;</li>
          <li>(d) It has the right to disclose to the other Party all information transmitted to other Party by it or on its behalf in the performance of the Services; and</li>
          <li>(e) There is no proceeding pending or, to the knowledge of the Party, threatened that challenges or could reasonably be expected to have a material adverse effect on the ability of the Party to perform and fulfil its obligations.</li>
        </ul>

        {/* 14. Warranty and Disclaimer */}
        <h2 className="mt-8 md:mt-10 text-base md:text-lg lg:text-xl font-semibold tracking-tight">
          14. Warranty and Disclaimer
        </h2>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          <strong>14.1</strong> Company shall use reasonable efforts consistent with prevailing industry standards to maintain the Services in a manner which minimizes errors and interruptions in the Services. The Customer hereby acknowledges and agrees that the Services may be temporarily unavailable for scheduled maintenance or for unscheduled emergency maintenance, either directly by the Company or due to denial of services by third-party service providers required by the Company to provide Services, other problems inherent in the use of the internet and electronic communication, telecommunications, force majeure, or because of other causes beyond Company's reasonable control.
        </p>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          <strong>14.2</strong> To the extent permitted by law and subject to the Service Levels provided herein, the Customer agrees that the Services shall not, at all times, be available or free from virus or bugs for reasons which are beyond the reasonable control of the Company nor does the Company warrants to the results that may be obtained from use of the Services. Accordingly, Company shall not be liable for any unauthorized disclosure, loss or destruction of Customer Data arising from such risks which are beyond the reasonable control of the Company. Except as expressly set forth in this section, the Services and implementation services are provided "as is" and the Company disclaims all warranties, express or implied, including, but not limited to, implied warranties of merchantability and fitness for a particular purpose and non-infringement. Customer may have other statutory rights, but the duration of statutorily required warranties, if any, will be limited to the shortest period permitted by law.
        </p>

        {/* 15. Confidentiality */}
        <h2 className="mt-8 md:mt-10 text-base md:text-lg lg:text-xl font-semibold tracking-tight">
          15. Confidentiality
        </h2>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          <strong>15.1</strong> The Customer acknowledges and agrees that all Confidential Information of InfoBay AI disclosed or made available to the Customer shall be maintained in strict confidence. The Customer shall not disclose, publish, transfer, or otherwise make available any Confidential Information of InfoBay AI to any person or entity without the prior written consent of InfoBay AI.
        </p>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          <strong>15.2</strong> The Customer agrees that, with respect to any Confidential Information disclosed by InfoBay AI (the "Discloser") to the Customer (the "Recipient"), the Customer shall:
        </p>
        <ul className="list-disc ml-6 mt-3 text-sm md:text-base text-zinc-300 leading-relaxed space-y-2">
          <li>(a) take all reasonable steps necessary to protect InfoBay AI's Confidential Information from unauthorized use, reproduction, or disclosure, which shall be no less than the degree of care used to protect its own confidential information of a similar nature;</li>
          <li>(b) use such Confidential Information solely for the purpose of receiving and using the Services provided by InfoBay AI;</li>
          <li>(c) not copy, reproduce, or permit the copying or reproduction of the Confidential Information, directly or indirectly, in whole or in part, except as strictly necessary for the use of the Services and subject to the retention of all proprietary notices and legends; and</li>
          <li>(d) not disclose, transfer, publish, or communicate the Confidential Information to any third party without the prior written consent of InfoBay AI.</li>
        </ul>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          <strong>15.3</strong> The confidentiality obligations set forth in this Clause shall not apply to any information that:
        </p>
        <ul className="list-disc ml-6 mt-3 text-sm md:text-base text-zinc-300 leading-relaxed space-y-2">
          <li>(a) is or becomes publicly available through no fault or breach of this Agreement by the Customer;</li>
          <li>(b) was lawfully known to the Customer prior to disclosure by InfoBay AI and not subject to any confidentiality obligation;</li>
          <li>(c) is required to be disclosed by law, regulation, or court order, provided that the Customer promptly notifies InfoBay AI in writing and cooperates with InfoBay AI in seeking protective treatment for such information; or</li>
          <li>(d) is independently developed by the Customer without reference to or use of InfoBay AI's Confidential Information, as demonstrated by written records.</li>
        </ul>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          <strong>15.4</strong> The obligations under this Clause (Confidentiality) shall survive the termination or expiration of the Service Order or this Agreement and shall remain in effect until such time as the Confidential Information lawfully enters the public domain.
        </p>

        {/* 16. Eligibility */}
        <h2 className="mt-8 md:mt-10 text-base md:text-lg lg:text-xl font-semibold tracking-tight">
          16. Eligibility
        </h2>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          Access to and use of the Site, Application, and Services ("Services") is strictly limited to individuals who have the legal capacity to enter into binding contracts under applicable Indian laws. The Services are intended solely for users who are eighteen (18) years of age or older.
        </p>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          If you are under eighteen (18) years of age, your parent or legal guardian may create an account on your behalf and assist you in enrolling in courses that are suitable for your age.
        </p>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          Access to and use of the Services is expressly prohibited for any individual whose membership has been suspended, revoked, or terminated by InfoBay AI for any reason whatsoever.
        </p>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          By accessing or using the Services, you represent, warrant, and covenant that you are at least eighteen (18) years of age. Any access or use of the Services by individuals under eighteen (18) years of age is strictly prohibited and may result in termination of access or other legal action.
        </p>

        {/* 17. Usage of Site, Application or Services */}
        <h2 className="mt-8 md:mt-10 text-base md:text-lg lg:text-xl font-semibold tracking-tight">
          17. Usage of Site, Application or Services
        </h2>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          The Site, Application, and Services offered by InfoBay AI are designed to provide users with access to advanced technology platforms, including artificial intelligence tools, Large Language Models (LLMs), hyperscale computing infrastructure, and related digital services. These Services are made available through the InfoBay AI platform and may include AI-powered applications, APIs, computing resources, research tools, and other technology solutions developed or hosted by InfoBay AI.
        </p>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          Users may browse certain portions of the platform as unregistered visitors; however, access to specific features, AI tools, computing resources, or services may require prior registration and the creation of an InfoBay AI account. By creating an account and accessing the platform, users agree to comply with the applicable terms governing the use of the Site, Application, and Services.
        </p>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          InfoBay AI provides an online technology platform that enables individuals, businesses, developers, and institutions to access and utilize AI-driven services, including Large Language Models, machine learning tools, data processing capabilities, and hyperscale computing environments. These services may be used for research, development, enterprise applications, automation, analytics, and other lawful purposes.
        </p>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          Through its platform, InfoBay AI may also provide tools, infrastructure, and integrations that enable developers, organizations, and partners to build, deploy, manage, and scale AI applications and digital solutions. Such capabilities may include access to computing resources, APIs, data processing tools, model interaction interfaces, and other supporting technologies.
        </p>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          Unless expressly stated otherwise on the InfoBay AI platform, InfoBay AI's role is limited to providing the technological infrastructure, platform services, and related tools that enable users to access and utilize AI capabilities and computing resources. Users remain solely responsible for the manner in which they use the platform, the data they submit, and the outputs generated through the Services.
        </p>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          In summary, InfoBay AI operates as a technology platform that enables users to access, develop, and deploy AI-powered solutions through a comprehensive digital ecosystem supporting Large Language Models (LLMs), artificial intelligence technologies, and hyperscale computing platforms.
        </p>

        {/* 18. Use of InfoBay AI Content */}
        <h2 className="mt-8 md:mt-10 text-base md:text-lg lg:text-xl font-semibold tracking-tight">
          18. Use of InfoBay AI Content
        </h2>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          InfoBay AI authorizes You, who are subject to these Terms, to view a single copy of the content available on or from InfoBay.ai and to access, use, download and print a single copy of the content available on or from all the InfoBay AI Site solely for Your personal, non-commercial use. The contents of InfoBay.ai, and of all other websites under the Company's control, whether partial or otherwise (InfoBay.ai and such other websites are sometimes collectively referred to as the "InfoBay AI Sites"), such as designs, text, graphics, images, videos, various pieces of information, logos, button icons, software, audio files and other InfoBay AI content (collectively, "InfoBay AI Content"), are protected under both India and foreign copyright, trademark and other laws. All InfoBay AI Content is the property of InfoBay AI or its licensors. The compilation (meaning the collection, arrangement, and assembly) of all content on the InfoBay AI Site is the exclusive property of InfoBay AI and is protected by Indian and international copyright, trademark, and other laws. Unauthorized use of the InfoBayAI's Content may violate these laws and/or applicable communications regulations and statutes and is strictly prohibited. You must preserve all copyrights, trademarks, service marks and other proprietary notices contained in the original InfoBay AI Content on any authorized copy that You make of the InfoBay AI Content. You may not sell or modify, reproduce, display, perform publicly with, distribute, or otherwise use InfoBayAI's Content in any way for any public or commercial purpose. You may also not do these in connection with products or services that do not belong to InfoBay AI, in any manner that is likely to cause confusion among consumers or otherwise infringes InfoBayAI's intellectual property rights.
        </p>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          Furthermore, any code that InfoBay AI creates to generate or display any InfoBayAI's Content or the pages making up any InfoBay AI Site is also protected by InfoBayAI's copyright and You may not copy or adapt such code.
        </p>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          You may not use any of the InfoBay AI Content on any other website or in a networked computer environment (including, without limitation, the uploading or republishing of InfoBayAI's Content on any Internet, Intranet or Extranet site or the incorporation of the InfoBayAI's Content in any other database or compilation, for any purpose). You shall not copy or adapt the HTML code that the Company creates to generate any InfoBay AI Content. You also shall not copy or adapt the pages making up any InfoBay AI Site which is also protected by the Company's copyright. Unless explicitly stated herein, nothing in these Terms shall be construed as conferring any license to intellectual property rights, whether by estoppel, implication or otherwise. This license is revocable at any time without notice and with or without cause.
        </p>

        {/* 19. InfoBay AI Site Restrictions */}
        <h2 className="mt-8 md:mt-10 text-base md:text-lg lg:text-xl font-semibold tracking-tight">
          19. InfoBay AI Site Restrictions
        </h2>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          Users shall not use any site of InfoBay AI in order to host, display, upload, modify, publish, transmit, update, distribute, share, store or destroy any material, including without limitation InfoBayAI's Content, in violation of any applicable law or regulation. Users also shall not use these in a manner that infringes the copyright, trademarks, trade secrets or other intellectual properties or proprietary rights of others. Users also shall not use any site of InfoBay AI in a manner that violates the privacy, publicity or other personal rights of others. They shall not use InfoBayAI's site(s) in a manner that is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, paedophilic, libellous, invasive of others privacy, threatening, abusive or hateful or racially, ethnically objectionable, disparaging, relating to encouraging money laundering or gambling or otherwise unlawful in any manner whatsoever. These manners also include the ways that harm minors, deceive or mislead the addressees about the origin of such messages or marcate pieces of information which are grossly offensive or menacing in nature, impersonate other person(s) or entity, contain software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of InfoBayAI's computer systems or site or InfoBayAI's users, customers' computer systems or sites, threaten the unity, integrity, defense, security or sovereignty of India. The users shall also not use the site(s) in manners that threaten friendly relations of India with its foreign states or threaten the public order or causes incitement resulting in a cognizable offence(s). These manners also include the ways that prevent investigation(s) of any offence or that may insult any other nation.
        </p>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          Users are also prohibited from violating or attempting to violate the security of any site of InfoBay AI, including, without limitations, the following activities:
        </p>
        <ul className="mt-3 ml-4 list-disc space-y-2 text-sm md:text-base text-zinc-300">
          <li>accessing data not intended for such user or logging into a server or account which the user is not authorized to access;</li>
          <li>attempting to probe, scan or test the vulnerability of a system or network or to breach security or authentication measures without proper authorization;</li>
          <li>attempting to interfere with service to any user, host or network, via means of submitting a virus to any InfoBay AI Site, and also "overloading", "flooding", "spamming", "mailbombing" or "crashing" it;</li>
          <li>forging any TCP/IP packet header or any part of the header information in any e-mail or newsgroup posting. Violations of system or network security may result in civil or criminal liabilities. The Company will investigate occurrences which may involve such violations and may involve, and cooperate with, law enforcement authorities in prosecuting users who are involved in such violations.</li>
        </ul>

        {/* 20. Registration Information */}
        <h2 className="mt-8 md:mt-10 text-base md:text-lg lg:text-xl font-semibold tracking-tight">
          20. Registration Information
        </h2>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          When You register with any InfoBay AI Site, You will be asked to provide the Company with certain information including, without limitation, a valid email address (your "Information"). In addition to agreeing to the Terms of Use and any privacy policy applicable to using any website of InfoBay AI, You declare that You understand and agree that the Company may disclose to third parties, on an anonymous basis, certain aggregate information contained in your registration application. The Company will not disclose to any third party your name, address, e-mail address or telephone number without your prior consent, except when it is necessary or appropriate to comply with applicable laws or in legal proceedings where such information is relevant.
        </p>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          The Company reserves the right to offer third party services and products to You based on the preferences that You identify during your registration and any time thereafter; such offers may be made by the Company or by third parties. Please see the Company's Privacy Statement for further details regarding your information.
        </p>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          Without limiting any of the other disclaimers of warranty set forth in these Terms of Use, InfoBay AI does not provide a warranty or guaranty or make any representation as to the quality or nature of any of the third party products or services purchased through InfoBay.ai or any other site of InfoBay AI. Any such undertaking, representation, warranty or guaranty would be furnished solely by the provider of the applicable class, or learning material(s), product(s) or service(s), under the terms agreed to by the provider.
        </p>

        {/* 21. Use of InfoBay AI Services */}
        <h2 className="mt-8 md:mt-10 text-base md:text-lg lg:text-xl font-semibold tracking-tight">
          21. Use of InfoBay AI Services
        </h2>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          The tools, platforms, and services provided by InfoBay AI, including Large Language Models (LLMs), hyperscale computing platforms, APIs, data processing tools, and related features, are intended to be used only for lawful, authorized, and permitted purposes. Users may access InfoBay AI Services for research, development, enterprise applications, automation, analytics, education, or other professional and technological purposes consistent with the intended use of the platform.
        </p>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          Your use of the InfoBay AI Services is also subject to any agreements or contracts you have with InfoBay AI. In the event of any conflict between these Terms of Service and the terms of any such agreements, the terms of the agreements shall prevail.
        </p>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          For the purposes of this clause, the term "use" includes any data, queries, prompts, or outputs that you submit, generate, publish, or display using InfoBay AI's Sites, Applications, or Services. Users are solely responsible for the content they provide, the applications they develop, and the manner in which they interact with the platform.
        </p>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          InfoBay AI provides access to LLMs, hyperscale computing platforms, and associated digital tools to facilitate AI development, research, and scalable computing solutions, and users must comply with all applicable laws, regulations, and acceptable use policies when using these Services.
        </p>

        {/* 22. Specific Prohibited Uses of InfoBay AI Services */}
        <h2 className="mt-8 md:mt-10 text-base md:text-lg lg:text-xl font-semibold tracking-tight">
          22. Specific Prohibited Uses of InfoBay AI Services
        </h2>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          The services provided by InfoBay AI, including Large Language Models (LLMs), hyperscale computing platforms, job posting tools, resume databases, and other digital features, are intended for lawful and authorized use only. Users may access InfoBay AI Services for employment, professional networking, research, AI development, enterprise applications, or other permitted activities consistent with the intended use of the platform.
        </p>
        <p className="mt-4 text-sm md:text-base text-zinc-300 leading-relaxed font-medium">
          Prohibited Activities: Users agree not to do any of the following while using InfoBay AI Services:
        </p>
        <ul className="mt-3 ml-4 list-disc space-y-2 text-sm md:text-base text-zinc-300">
          <li>Transmit, post, distribute, store, or destroy any materials, including InfoBay AI content, in violation of applicable laws or regulations, including laws governing personal data, privacy, or InfoBay AI's Privacy Policy.</li>
          <li>Post resumes or apply for jobs on behalf of another individual without proper authorization.</li>
          <li>Redirect employer communications to agents, third parties, or intermediaries.</li>
          <li>Post multiple copies of the same resume to the public.</li>
          <li>Solicit passwords, credentials, or personally identifiable information from other users.</li>
          <li>Post jobs or content for competitors of InfoBay AI or include links to competing sites.</li>
          <li>Include hyperlinks, email addresses, hidden keywords, HTML tags, or misleading content in job postings.</li>
          <li>Post jobs for modeling, talent scouting, or similar roles unless explicitly permitted.</li>
          <li>Use the resume database for any purpose other than lawful recruitment, including selling or promoting products or services.</li>
          <li>Submit incomplete, false, or inaccurate information or information that does not belong to the user.</li>
          <li>Post franchise schemes, pyramid schemes, distributorships, or other business opportunities requiring upfront payment, recruitment of members, or commission-only structures (except lawful commission-only postings clearly describing the role).</li>
          <li>Send unsolicited communications (email, phone, fax) promoting products or services to users.</li>
          <li>Delete, revise, or tamper with content posted by other users.</li>
          <li>Take actions that impose an unreasonable load on InfoBay AI's infrastructure.</li>
          <li>Use automated tools, robots, scrapers, or similar data extraction methods except via authorized APIs.</li>
          <li>Attempt to reverse engineer, decompile, or tamper with InfoBay AI's software or AI models.</li>
          <li>Aggregate, copy, or duplicate InfoBay AI content, including expired postings, outside permitted uses.</li>
          <li>Frame or link to InfoBay AI content misleadingly or in violation of these Terms.</li>
          <li>Use InfoBay AI Services for unlawful purposes, illegal activity, or to post content that is offensive, abusive, threatening, discriminatory, defamatory, obscene, sexually explicit, or otherwise harmful, as determined at InfoBay AI's sole discretion.</li>
          <li>Insert personal URLs, weblinks, email addresses, or websites in job postings.</li>
          <li>Submit sensitive, confidential, or personally identifiable third-party data to AI Services without proper consent.</li>
        </ul>
        <p className="mt-4 text-sm md:text-base text-zinc-300 leading-relaxed font-medium">
          Enforcement:
        </p>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          InfoBay AI, as a reliable data partner supporting LLMs and hyperscale computing platforms, reserves the right, at its sole discretion, to restrict, suspend, or terminate access to the platform for users violating these rules. The Company may remove or block offending content, request the removal of user submissions, and initiate legal proceedings as appropriate. InfoBay AI is not liable for any consequences arising from enforcement actions taken in accordance with this clause.
        </p>

        {/* 23. User Content and Submissions */}
        <h2 className="mt-8 md:mt-10 text-base md:text-lg lg:text-xl font-semibold tracking-tight">
          23. User Content and Submissions
        </h2>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          You are solely responsible for your information, content, messages or other information ("User Content") pertaining to the My InfoBay AI Account that You submit, publish or display (hereinafter, "post") on any of the InfoBay AI Sites or transmit to other Users. By posting User Content to any of the InfoBay AI Sites, You automatically grant, and You represent and warrant that You have the right to grant, to InfoBay AI an irrevocable, perpetual, non-exclusive, fully paid, worldwide license to use, copy, perform, display, and distribute such User Content and to prepare derivative works of, or incorporate into other works, such User Content, and to grant and authorize sublicenses thereof.
        </p>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          By posting User Content to any public or non-public area of any of InfoBayAI's Sites, including message boards, forums, contests and chat rooms, You grant the Company and its parent company and affiliates the loyalty-free, perpetual, irrevocable, sublicensable (through multiple tiers), non-exclusive right (including moral rights) and license to use, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, communicate to the public, perform and display the User Content (in whole or in part) worldwide and/or to incorporate it in other works in any form, media, or technology now known or later developed, for the full term of any rights that may exist in such content.
        </p>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          You also warrant that the holder of any rights, including moral rights in such content, has completely and effectively waived all such rights and validly and irrevocably granted to You the right to grant the license stated above. You also permit any User to access, display, view, store and reproduce such User Content for personal use. Subject to the foregoing, the owner of such User Content as placed on any of InfoBayAI's sites, retain all the rights that may exist in such User Content.
        </p>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          You agree that any email sent by an employer to a job seeker for any prospective job opportunity through InfoBayAI's website may be stored at the InfoBay AI account of the said jobseeker for at least a period of 7 days, to enable the said jobseeker to access the email, as sent by the employer, to take a conscious decision about the job offer in the said email.
        </p>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          The Company acts as a passive conduit for the online distribution and publication of User Content and has no obligation to screen communications or information in advance and is not responsible for screening or monitoring of the User Content posted by the Users. However, the Company may review and delete any User Content that, in the sole judgment of InfoBay AI, violates these Terms of Use, violates applicable law, rule or regulation, is offensive or illegal or violates the rights of, harms or threatens the safety of Users of any of the sites of InfoBay AI. The Company reserves the right to expel Users and prevent their further access to all the sites of InfoBay AI for violating the Terms of Use or applicable law, rule or regulation. The Company also has the right to remove User Content which is in violation of the Terms of Use, is abusive, illegal, or disruptive.
        </p>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          The Company reserves the right to archive the user content folders which were not being accessed for a period of 6 months or more by the relevant users after its last access. In such event users will be able to access the archived folders with minor limitations including but not limited to non-availability of the options of moving those to other folders, renew jobs associated with the said folders. The Company may take any legal action with respect to the User Content that it deems necessary or appropriate in its sole discretion if it believes the Content may create liability for the Company or may cause the Company to lose (in whole or in parts) the services of its ISPs or other suppliers.
        </p>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          The following is a partial list of User Content that is prohibited on the various sites of InfoBay AI. The list below is for illustration only and is not a complete list of all prohibited User Content. Hence, InfoBay AI may prohibit the User Content that:
        </p>
        <ul className="mt-3 ml-4 list-disc space-y-2 text-sm md:text-base text-zinc-300">
          <li>is implicitly or explicitly offensive, such as User Content that engages in, endorses or promotes racism, bigotry, hatred or physical harm of any kind against any group or individual;</li>
          <li>harasses, incites harassment or advocates harassment of another person, any group or people;</li>
          <li>involves the transmission of "junk mail", "chain letters," or unsolicited mass mailing or "spamming";</li>
          <li>promotes or endorses false or misleading information or illegal activities or promotes the conduct that is abusive, threatening, obscene, defamatory or libelous;</li>
          <li>promotes or endorses an illegal or unauthorized copy of another person's copyrighted work, such as providing or making available pirated computer programs or links to them, providing or making available information to circumvent manufacture-installed copy-protect devices, or providing or making available pirated music or other media or links to pirated music or other media files;</li>
          <li>contains restricted or password enabled accessible pages, or hidden pages or images;</li>
          <li>displays or links to pornographic, indecent or sexually explicit material of any kind;</li>
          <li>provides or links to material that exploits people under the age of 18 in a sexual, violent or another manner, or solicits personal information from anyone under 18;</li>
          <li>provides instructional information about illegal activities or other activities prohibited by these Terms, including without limitation, making or buying illegal weapons, violating someone's privacy, or provides or creates computer viruses or pirating any media;</li>
          <li>solicits passwords or personal identifying information from other Users;</li>
        </ul>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          InfoBay AI reserves the right in its sole discretion to investigate and take legal action against anyone who engages in any illegal or prohibited conduct or otherwise violates these Terms of Use, including without limitation, removing the User Content from InfoBayAI's Sites and/or terminating the offending User's ability to access InfoBayAI's Sites and/or use InfoBayAI's services. The Company may take any other action with respect to User Content or User actions that it deems necessary or appropriate in its sole discretion if it believes it may create liability for the Company or may cause the Company to lose (in whole or in parts) the services of its ISPs or other suppliers.
        </p>

        {/* 24. Registration and Password */}
        <h2 className="mt-8 md:mt-10 text-base md:text-lg lg:text-xl font-semibold tracking-tight">
          24. Registration and Password
        </h2>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          You are responsible for maintaining the confidentiality of your account access information and passwords. You shall be responsible for all uses of your Web Site registrations and passwords, whether or not authorized by You. You are not authorized to share your password or other pieces of information related to the access of your account, with any other party, temporarily or permanently. A breach of this obligation may tantamount to disabling the InfoBay AI account and InfoBay AI Services. You agree to immediately notify the Company of any unauthorized use of your account, and passwords.
        </p>

        {/* 25. Data Privacy and SMS Alerts */}
        <h2 className="mt-8 md:mt-10 text-base md:text-lg lg:text-xl font-semibold tracking-tight">
          25. Data Privacy and SMS Alerts
        </h2>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          In the context of the service of 'alerts' being introduced by InfoBay AI, the candidate consents to the use of his personal data in the form of cellular phone number(s) being used by InfoBay AI to forward relevant job alerts and other information as and when they become available.
        </p>

        {/* 26. Identification of Agent */}
        <h2 className="mt-8 md:mt-10 text-base md:text-lg lg:text-xl font-semibold tracking-tight">
          26. Identification of Agent to Receive Notification and Elements of Notification of Claimed Copyright Infringements
        </h2>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          If you believe that your copyrighted work has been uploaded, posted, or copied to any InfoBay AI Web Site and is accessible on such InfoBay AI Site in a way that constitutes copyright infringement, please notify us by providing our designated copyright agent with the following information:
        </p>
        <ul className="mt-3 ml-4 list-disc space-y-2 text-sm md:text-base text-zinc-300">
          <li>The physical or electronic signature of either the copyright owner or of a person authorized to act on the owner's behalf;</li>
          <li>A description of the copyrighted work you claim has been infringed, and a description of the activity that you claim to be infringing;</li>
          <li>Identification of the URL or other specific location on this website where the material or activity you claim to be infringing is located or is occurring; you must include enough information to allow us to locate the material or the activity;</li>
          <li>Your name, address, telephone number and, if you have one, your e-mail address;</li>
          <li>A statement by you that you have a good faith belief that the use of the copyrighted work in the manner you are complaining of is not authorized by the copyright owner, any agent of the copyright owner, or the law; and</li>
          <li>A statement by you, made under penalty of perjury, that the information you have provided in your notice is accurate and that you are either the copyright owner or are authorized to act on behalf of the copyright owner.</li>
        </ul>

        <h2 className="mt-8 md:mt-10 text-base md:text-lg lg:text-xl font-semibold tracking-tight text-white">
          By post/mail:
        </h2>
        <address className="mt-4 font-medium text-zinc-300 italic">
          The InfoBay AI Limited.<br />
          5/142 HIG Awas Vikas Colony,<br />
          Farrukhabad, U.P.,<br />
          India.<br />
          PIN – 209625
        </address>

        <h2 className="mt-10 text-base md:text-lg lg:text-xl font-semibold tracking-tight text-white">
          By email:
        </h2>
        <p className="mt-4">
          <a
            href="mailto:hello@InfoBay.ai"
            className="text-sky-400 hover:text-sky-300 underline italic font-medium"
          >
            hello@InfoBay.ai
          </a>
        </p>

        {/* 27. Intellectual Property Rights */}
        <h2 className="mt-8 md:mt-10 text-base md:text-lg lg:text-xl font-semibold tracking-tight">
          27. Intellectual Property Rights
        </h2>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          "Intellectual Property Rights" means any and all intellectual property rights whether registered or unregistered, and all applications for and renewals or extensions of such rights, including rights comprising or relating to: (a) patents, patent disclosures and inventions (whether patentable or not); (b) trademarks, service marks, trade dress, trade names, logos, corporate names and domain names, together with all of the goodwill associated therewith; (c) works of authorship, designs, copyrights and copyrightable works (including computer programs) and rights in data and databases; (d) trade secrets, know-how and other confidential information; and (e) all similar or equivalent rights or forms of protection.
        </p>

        {/* 28. Policy Regarding Termination */}
        <h2 className="mt-8 md:mt-10 text-base md:text-lg lg:text-xl font-semibold tracking-tight">
          28. Policy Regarding Termination of Users Who Infringe the Copyright or Other Intellectual Property Rights of Others
        </h2>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          InfoBay AI Limited., and all our affiliated companies respect the intellectual properties of others, and we ask our users, account holders and content partners to do the same. The unauthorized reproduction, copying, distribution, modification, public display or public performance of copyrighted works constitute the infringement of the rights of the owners of the copyright. As a condition to your use of InfoBay.ai, You agree not to use InfoBay.ai or any other site of InfoBay AI to infringe the intellectual property rights of others in any way. We will terminate the accounts of any InfoBay.ai account holders, and block access to InfoBay.ai and/or the other InfoBay AI Sites of any Users who are repeat infringers of the copyrights. We will also terminate or block the access of the infringers of others' intellectual property rights. We reserve the right to take these actions at any time, in our sole discretion, with or without notice, and without any liability to the account holder who is terminated or to the User whose access is blocked.
        </p>

        {/* 29. Governing Law */}
        <h2 className="mt-8 md:mt-10 text-base md:text-lg lg:text-xl font-semibold tracking-tight">
          29. Governing Law
        </h2>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          <strong>29.1</strong> The Terms of Service and Service Order shall be governed by laws in force in India, and shall be subject to the exclusive jurisdiction of courts at Lucknow, India.
        </p>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          <strong>29.2</strong> Any question regarding its existence, validity or termination, shall be referred to, arbitration in Lucknow in accordance with the Arbitration and Conciliation Act, 1996 ("Arbitration Act") for the time being in force, which rules are deemed to be incorporated by reference in this (Dispute Resolution). The arbitral tribunal shall consist of a sole arbitrator appointed mutually by the Parties to the dispute. In case the Parties to the dispute do not agree upon or appoint a sole arbitrator within a period of 30 (Thirty) days, any of the parties to the dispute can approach a competent court of jurisdiction to request appointment of a sole arbitrator. Subject to the aforesaid, each Party to an arbitration shall bear its own expenses in relation thereto, including, but not limited to, such Party's attorney's fees and expenses, and fees of the arbitrator shall be borne equally by the Parties disclaims all warranties, whether express or implied, including the warranty of merchant ability, fitness for particular purpose and non-infringement. InfoBay AI makes no warranties about the accuracy, reliability, completeness, or timeliness of the InfoBay AI content, services, software, text, graphics, and links.
        </p>

        {/* 30. Disclaimer of Consequential Damages & Limitation of Liability */}
        <h2 className="mt-8 md:mt-10 text-base md:text-lg lg:text-xl font-semibold tracking-tight">
          30. Disclaimer of Consequential Damages &amp; Limitation of Liability
        </h2>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          To the fullest extent possible by law, in no event shall InfoBay AI, its suppliers, or any third parties mentioned on any InfoBay AI site be liable for any damages whatsoever (including, without limitation, incidental and consequential damages, lost profits, or damages resulting from lost data, lost employment opportunity or business interruption) resulting from the use or inability to use any InfoBay AI site and the InfoBay AI content, whether based on warranty, contract, tort, or any other legal theory, and whether or not InfoBay AI is advised of the possibility of such damages. Limitation of Liability To the fullest extent possible by law, InfoBayAI's maximum liability arising out of or in connection with any InfoBay AI site or your use of the InfoBay AI content, regardless of the cause of action (whether in contract, tort, breach of warranty or otherwise), will not exceed INR 1,000/-.
        </p>

        {/* 31. Links to Other Sites */}
        <h2 className="mt-8 md:mt-10 text-base md:text-lg lg:text-xl font-semibold tracking-tight">
          31. Links to Other Sites
        </h2>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          All the sites of InfoBay AI contain links to third-party web sites. These links are provided solely as a convenience to You and not as an endorsement, by InfoBay AI, of the contents on such third-party web sites. InfoBay AI is not responsible for the content of linked third-party sites and does not make any representations regarding the content or accuracy of materials on such third party Web sites. If You decide to access linked third-party Web sites, it is understood, therefore, that, You do so at Your own risk.
        </p>

        {/* 32. No Resale or Unauthorized Commercial Use */}
        <h2 className="mt-8 md:mt-10 text-base md:text-lg lg:text-xl font-semibold tracking-tight">
          32. No Resale or Unauthorized Commercial Use
        </h2>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          You agree not to resell or assign Your rights or obligations under these Terms. You also agree not to make any unauthorized commercial use of any InfoBay AI Site.
        </p>

        {/* 33. Redressal of Users Grievance */}
        <h2 className="mt-8 md:mt-10 text-base md:text-lg lg:text-xl font-semibold tracking-tight">
          33. Redressal of Users Grievance
        </h2>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          The Company has designated Rohit Manglik as Grievance Officer to redress the grievances of the users. The aggrieved user may submit their grievances by addressing them to:
        </p>

        <h2 className="mt-8 md:mt-10 text-base md:text-lg lg:text-xl font-semibold tracking-tight text-white">
          By post/mail:
        </h2>
        <address className="mt-4 font-medium text-zinc-300 italic">
          The InfoBay AI Limited.<br />
          5/142 HIG Awas Vikas Colony,<br />
          Farrukhabad, U.P.,<br />
          India.<br />
          PIN – 209625
        </address>

        <h2 className="mt-10 text-base md:text-lg lg:text-xl font-semibold tracking-tight text-white">
          By email:
        </h2>
        <p className="mt-4">
          <a
            href="mailto:hello@InfoBay.ai"
            className="text-sky-400 hover:text-sky-300 underline italic font-medium"
          >
            hello@InfoBay.ai
          </a>
        </p>

        {/* 34. Response Timelines */}
        <h2 className="mt-8 md:mt-10 text-base md:text-lg lg:text-xl font-semibold tracking-tight">
          34. Response Timelines
        </h2>
        <ul className="list-disc ml-6 mt-3 text-sm md:text-base text-zinc-300 leading-relaxed space-y-1">
          <li>InfoBay AI will acknowledge receipt of the grievance within 48 hours.</li>
          <li>We will make reasonable efforts to resolve the grievance within 15 working days, subject to the complexity of the issue and applicable legal requirements.</li>
        </ul>

        {/* 35. Additional Terms of Use & Terms and Termination */}
        <h2 className="mt-8 md:mt-10 text-base md:text-lg lg:text-xl font-semibold tracking-tight">
          35. Additional Terms of Use &amp; Terms and Termination
        </h2>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          Certain areas of InfoBay.ai and the other InfoBay AI Sites are subject to additional terms of use. By using such areas, or any part thereof, You agree to be bound by the additional terms of use applicable to such areas. These Terms of Use will remain in full force and effect while You are a User of InfoBay.ai at any level. The Company reserves the right, at its sole discretion, to pursue all of its legal remedies, including but not limited to deletion of your User Content from InfoBay.ai and the other InfoBay AI Sites and immediate termination of your registration with or ability to access InfoBay.ai and the other InfoBay AI Sites and/or any other services provided to You by the Company, upon any breach by You of these Terms of Use or if the Company is unable to verify or authenticate any information You submit to InfoBay.ai or to other InfoBay AI Sites. Even after You are no longer a User of InfoBay.ai, certain provisions of these Terms of Use will remain in effect, including Sections 2, 6, through 10 to 22 as well as the "Additional Terms of Use."
        </p>

        {/* 36. InfoBay AI Video Service. Additional Terms of Use */}
        <h2 className="mt-8 md:mt-10 text-base md:text-lg lg:text-xl font-semibold tracking-tight">
          36. InfoBay AI Video Service. Additional Terms of Use
        </h2>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          Your Acceptance of The Additional Terms of Use for Using InfoBay AI Video Service Your access and/or use of this InfoBay AI Video Service is subject to these Additional Terms of Use besides the Terms of Use (click at http://InfoBay.ai/terms-and-conditions) and Privacy Commitment (click at http://www.InfoBay.ai/privacy) enshrined and specified on the homepage of the website: http://www.InfoBay.ai (hereinafter referred to as "InfoBay AI Website") which are additional and supplementary and are incorporated herein by reference. By accessing or using this InfoBay AI Video Service you agree to be bound by these Additional Terms of Use, the said Terms of Use and Privacy Commitment, or any amendments thereof, applicable laws, rules and regulations governing this website. Please do not access and/or use this website if you do not agree with any of the terms and conditions stated herein or under the said Terms of Use and/or Privacy Statement enshrined and specified on the InfoBay AI Website. You also hereby agree and acknowledge that you are eligible and have contractual capacity to access or use this InfoBay AI Video Service and InfoBay AI Website. The terms "You" and "User" as used herein refer to all individuals and/or entities accessing this website for any reason whatsoever.
        </p>

        {/* 37. Video Content Submissions & InfoBayAI's Rights */}
        <h2 className="mt-8 md:mt-10 text-base md:text-lg lg:text-xl font-semibold tracking-tight">
          37. Video Content Submissions &amp; InfoBayAI's Rights
        </h2>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          Sections describing permitted submissions, licenses granted to InfoBay AI, prohibited content, and InfoBayAI's right to remove or monetize submissions are included here in full in the original document.
        </p>

        {/* 38. Child Safety Policy */}
        <h2 className="mt-8 md:mt-10 text-base md:text-lg lg:text-xl font-semibold tracking-tight">
          38. Child Safety Policy (Summary)
        </h2>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          InfoBay AI is committed to ensuring the safety, dignity, and well-being of all children who come into contact with its services, personnel, or stakeholders. This Child Safety Policy applies to all individuals and entities associated with InfoBay AI.
        </p>

        {/* 39. Waiver of Claims & Indemnity Provision */}
        <h2 className="mt-8 md:mt-10 text-base md:text-lg lg:text-xl font-semibold tracking-tight">
          39. Waiver of Claims &amp; Indemnity Provision
        </h2>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          You hereby waive all claims against InfoBay AI and indemnify its directors, employees, authorized representatives and agents from any and all liability for claims, damages, costs and expenses arising out of or in any way concerned with the use of the InfoBay AI Video Service and your violation of these Additional Terms. Failure or delay by Infobay AI in enforcing any right or provision under these Terms shall not constitute a waiver of such right, nor shall it prevent Infobay AI from enforcing the same in the future.
        </p>

        {/* 40. Disclaimer & Limitation of Liability (Video Service) */}
        <h2 className="mt-8 md:mt-10 text-base md:text-lg lg:text-xl font-semibold tracking-tight">
          40. Disclaimer &amp; Limitation of Liability (Video Service)
        </h2>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          You agree and acknowledge that your use and access of the InfoBay AI video service and InfoBay AI website shall be at your sole risk, responsibility, and consequences. To the fullest extent permitted by law, InfoBay AI, its officers, directors, employees, authorized representatives, and agents disclaim all warranties, express or implied, in connection with the InfoBay AI video service and InfoBay AI website and your use thereof.
        </p>

        {/* 41. Copyright Policy & Force Majeure */}
        <h2 className="mt-8 md:mt-10 text-base md:text-lg lg:text-xl font-semibold tracking-tight">
          41. Copyright Policy &amp; Force Majeure
        </h2>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          InfoBay AI respects copyright law and may suspend or terminate accounts of repeat infringers. Infobay AI shall not be liable for any delay or failure in performance resulting from events beyond its reasonable control, including but not limited to natural disasters, strikes, pandemics, governmental actions, technical failures, or internet/network disruptions.
        </p>

        {/* 42. Severability */}
        <h2 className="mt-8 md:mt-10 text-base md:text-lg lg:text-xl font-semibold tracking-tight">
          42. Severability
        </h2>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          If any provision of these Terms is found to be invalid, illegal, or unenforceable under applicable law, such provision shall be deemed severed, and the remaining provisions shall continue in full force and effect.
        </p>

        {/* 43. Feedback */}
        <h2 className="mt-8 md:mt-10 text-base md:text-lg lg:text-xl font-semibold tracking-tight">
          43. Feedback
        </h2>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          We welcome and encourage you to provide feedback. By submitting Feedback, you acknowledge that all Feedback becomes the sole and exclusive property of InfoBay AI.
        </p>

        {/* 44. Assignment */}
        <h2 className="mt-8 md:mt-10 text-base md:text-lg lg:text-xl font-semibold tracking-tight">
          44. Assignment
        </h2>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          You may not assign or transfer your rights or obligations under these Terms without prior written consent from InfoBay AI.
        </p>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          InfoBay AI may assign or transfer its rights and obligations without restriction, including in connection with a merger, acquisition, or sale of assets.
        </p>

        {/* 45. Notices */}
        <h2 className="mt-8 md:mt-10 text-base md:text-lg lg:text-xl font-semibold tracking-tight">
          45. Notices
        </h2>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          All notices under these Terms shall be provided:
        </p>
        <ul className="list-disc ml-6 mt-2 text-sm md:text-base text-zinc-300 leading-relaxed space-y-1">
          <li>Electronically via the Platform, email, or SMS</li>
          <li>By postal mail to the registered address of the User (if applicable)</li>
          <li>Such notices shall be deemed delivered when sent.</li>
        </ul>

        {/* 47. Customer Care & Amendment in Terms of Use */}
        <h2 className="mt-8 md:mt-10 text-base md:text-lg lg:text-xl font-semibold tracking-tight">
          47. Customer Care &amp; Amendment in Terms of Use
        </h2>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          If you face any issues, please contact us at{" "}
          <a
            href="mailto:hello@InfoBay.ai"
            className="text-sky-400 hover:text-sky-300 underline italic font-medium"
          >
            hello@InfoBay.ai
          </a>. InfoBay AI may amend these Terms at any time by posting updates on the website.
        </p>
        <p className="mt-3 text-sm md:text-base text-zinc-300 leading-relaxed">
          InfoBay AI may amend these Terms at any time by posting updates on the website.
        </p>
        <ul className="list-decimal ml-6 mt-2 space-y-1 text-sm md:text-base text-zinc-300 leading-relaxed">
          <li>Changes will be posted on the Platform, and the updated Terms shall be effective immediately upon posting.</li>
          <li>Your continued use of the Platform constitutes acceptance of the revised Terms.</li>
        </ul>

      </div>
    </main>
  );
};

export default TermsOfService;